// Code generated by Fabrica v0.4.10-7-g53b0071 (commit: 53b0071). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /users (User operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("User", "user")

	return nil
}

// RegisterGeneratedRoutes registers all generated resource routes.
// The router passed to this function should already have middleware applied in main.go.
// Public service routes such as /health, /openapi.json, and /docs are registered
// in cmd/server/main.go so they remain outside auth middleware.
func RegisterGeneratedRoutes(r chi.Router) {
	// Routes inherit middleware from the router passed by main.go

	// User routes
	r.Route("/users", func(resource chi.Router) {
		resource.Get("/", GetUsers)
		resource.Post("/", CreateUser)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetUser)
			item.Put("/", UpdateUser)
			item.Patch("/", PatchUser)
			item.Delete("/", DeleteUser)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateUserStatus)
				status.Patch("/", PatchUserStatus)
			})
		})
	})

}
