// Code generated by Fabrica v0.4.10-7-g53b0071 (commit: 53b0071). DO NOT EDIT.
// Template: server/version.go.tmpl
// Generated: 2026-09-02T17:46:33Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// Service version information - set via ldflags at build time
var (
	serviceVersion = "dev"
	serviceCommit  = "none"
	serviceDate    = "unknown"
)

// fabricaVersion is embedded at generation time
const fabricaVersion = "v0.4.10-7-g53b0071"

func serviceVersionString() string {
	if serviceCommit == "none" && serviceDate == "unknown" {
		return serviceVersion
	}
	if serviceCommit == "none" {
		return fmt.Sprintf("%s (built: %s)", serviceVersion, serviceDate)
	}
	if serviceDate == "unknown" {
		return fmt.Sprintf("%s (commit: %s)", serviceVersion, serviceCommit)
	}
	return fmt.Sprintf("%s (commit: %s, built: %s)", serviceVersion, serviceCommit, serviceDate)
}

// NewVersionCommand creates the version command for the server
func NewVersionCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version information",
		Long:  `Print version information for user_service`,
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("user_service version %s\n", serviceVersion)
			if serviceCommit != "none" {
				fmt.Printf("  commit: %s\n", serviceCommit)
			}
			if serviceDate != "unknown" {
				fmt.Printf("  built:  %s\n", serviceDate)
			}
			fmt.Printf("  generated by: Fabrica %s\n", fabricaVersion)
		},
	}
}
