// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openchami/named-resource-service/internal/storage/ent/named"
)

// NamedCreate is the builder for creating a Named entity.
type NamedCreate struct {
	config
	mutation *NamedMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *NamedCreate) SetUID(v string) *NamedCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *NamedCreate) SetName(v string) *NamedCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *NamedCreate) SetNamespace(v string) *NamedCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_c *NamedCreate) SetNillableNamespace(v *string) *NamedCreate {
	if v != nil {
		_c.SetNamespace(*v)
	}
	return _c
}

// SetAPIVersion sets the "api_version" field.
func (_c *NamedCreate) SetAPIVersion(v string) *NamedCreate {
	_c.mutation.SetAPIVersion(v)
	return _c
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_c *NamedCreate) SetNillableAPIVersion(v *string) *NamedCreate {
	if v != nil {
		_c.SetAPIVersion(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *NamedCreate) SetKind(v string) *NamedCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *NamedCreate) SetNillableKind(v *string) *NamedCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NamedCreate) SetCreatedAt(v time.Time) *NamedCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NamedCreate) SetNillableCreatedAt(v *time.Time) *NamedCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NamedCreate) SetUpdatedAt(v time.Time) *NamedCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NamedCreate) SetNillableUpdatedAt(v *time.Time) *NamedCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetResourceVersion sets the "resource_version" field.
func (_c *NamedCreate) SetResourceVersion(v string) *NamedCreate {
	_c.mutation.SetResourceVersion(v)
	return _c
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_c *NamedCreate) SetNillableResourceVersion(v *string) *NamedCreate {
	if v != nil {
		_c.SetResourceVersion(*v)
	}
	return _c
}

// SetSpecData sets the "spec_data" field.
func (_c *NamedCreate) SetSpecData(v json.RawMessage) *NamedCreate {
	_c.mutation.SetSpecData(v)
	return _c
}

// SetSpecName sets the "spec_name" field.
func (_c *NamedCreate) SetSpecName(v string) *NamedCreate {
	_c.mutation.SetSpecName(v)
	return _c
}

// SetNillableSpecName sets the "spec_name" field if the given value is not nil.
func (_c *NamedCreate) SetNillableSpecName(v *string) *NamedCreate {
	if v != nil {
		_c.SetSpecName(*v)
	}
	return _c
}

// SetSpecAltName sets the "spec_alt_name" field.
func (_c *NamedCreate) SetSpecAltName(v string) *NamedCreate {
	_c.mutation.SetSpecAltName(v)
	return _c
}

// SetSpecNumber sets the "spec_number" field.
func (_c *NamedCreate) SetSpecNumber(v int) *NamedCreate {
	_c.mutation.SetSpecNumber(v)
	return _c
}

// SetNillableSpecNumber sets the "spec_number" field if the given value is not nil.
func (_c *NamedCreate) SetNillableSpecNumber(v *int) *NamedCreate {
	if v != nil {
		_c.SetSpecNumber(*v)
	}
	return _c
}

// SetSpecSomethingOrNothing sets the "spec_something_or_nothing" field.
func (_c *NamedCreate) SetSpecSomethingOrNothing(v string) *NamedCreate {
	_c.mutation.SetSpecSomethingOrNothing(v)
	return _c
}

// SetNillableSpecSomethingOrNothing sets the "spec_something_or_nothing" field if the given value is not nil.
func (_c *NamedCreate) SetNillableSpecSomethingOrNothing(v *string) *NamedCreate {
	if v != nil {
		_c.SetSpecSomethingOrNothing(*v)
	}
	return _c
}

// Mutation returns the NamedMutation object of the builder.
func (_c *NamedCreate) Mutation() *NamedMutation {
	return _c.mutation
}

// Save creates the Named in the database.
func (_c *NamedCreate) Save(ctx context.Context) (*Named, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NamedCreate) SaveX(ctx context.Context) *Named {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NamedCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NamedCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NamedCreate) defaults() {
	if _, ok := _c.mutation.APIVersion(); !ok {
		v := named.DefaultAPIVersion
		_c.mutation.SetAPIVersion(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := named.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := named.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := named.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		v := named.DefaultResourceVersion
		_c.mutation.SetResourceVersion(v)
	}
	if _, ok := _c.mutation.SpecNumber(); !ok {
		v := named.DefaultSpecNumber
		_c.mutation.SetSpecNumber(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NamedCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Named.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := named.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Named.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Named.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := named.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Named.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIVersion(); !ok {
		return &ValidationError{Name: "api_version", err: errors.New(`ent: missing required field "Named.api_version"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Named.kind"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Named.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Named.updated_at"`)}
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		return &ValidationError{Name: "resource_version", err: errors.New(`ent: missing required field "Named.resource_version"`)}
	}
	if _, ok := _c.mutation.SpecAltName(); !ok {
		return &ValidationError{Name: "spec_alt_name", err: errors.New(`ent: missing required field "Named.spec_alt_name"`)}
	}
	if v, ok := _c.mutation.SpecAltName(); ok {
		if err := named.SpecAltNameValidator(v); err != nil {
			return &ValidationError{Name: "spec_alt_name", err: fmt.Errorf(`ent: validator failed for field "Named.spec_alt_name": %w`, err)}
		}
	}
	return nil
}

func (_c *NamedCreate) sqlSave(ctx context.Context) (*Named, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NamedCreate) createSpec() (*Named, *sqlgraph.CreateSpec) {
	var (
		_node = &Named{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(named.Table, sqlgraph.NewFieldSpec(named.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(named.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(named.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(named.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.APIVersion(); ok {
		_spec.SetField(named.FieldAPIVersion, field.TypeString, value)
		_node.APIVersion = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(named.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(named.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(named.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ResourceVersion(); ok {
		_spec.SetField(named.FieldResourceVersion, field.TypeString, value)
		_node.ResourceVersion = value
	}
	if value, ok := _c.mutation.SpecData(); ok {
		_spec.SetField(named.FieldSpecData, field.TypeJSON, value)
		_node.SpecData = value
	}
	if value, ok := _c.mutation.SpecName(); ok {
		_spec.SetField(named.FieldSpecName, field.TypeString, value)
		_node.SpecName = value
	}
	if value, ok := _c.mutation.SpecAltName(); ok {
		_spec.SetField(named.FieldSpecAltName, field.TypeString, value)
		_node.SpecAltName = value
	}
	if value, ok := _c.mutation.SpecNumber(); ok {
		_spec.SetField(named.FieldSpecNumber, field.TypeInt, value)
		_node.SpecNumber = value
	}
	if value, ok := _c.mutation.SpecSomethingOrNothing(); ok {
		_spec.SetField(named.FieldSpecSomethingOrNothing, field.TypeString, value)
		_node.SpecSomethingOrNothing = value
	}
	return _node, _spec
}

// NamedCreateBulk is the builder for creating many Named entities in bulk.
type NamedCreateBulk struct {
	config
	err      error
	builders []*NamedCreate
}

// Save creates the Named entities in the database.
func (_c *NamedCreateBulk) Save(ctx context.Context) ([]*Named, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Named, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NamedMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NamedCreateBulk) SaveX(ctx context.Context) []*Named {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NamedCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NamedCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
