// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/openchami/named-resource-service/internal/storage/ent/named"
	"github.com/openchami/named-resource-service/internal/storage/ent/predicate"
)

// NamedUpdate is the builder for updating Named entities.
type NamedUpdate struct {
	config
	hooks    []Hook
	mutation *NamedMutation
}

// Where appends a list predicates to the NamedUpdate builder.
func (_u *NamedUpdate) Where(ps ...predicate.Named) *NamedUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NamedUpdate) SetName(v string) *NamedUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableName(v *string) *NamedUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *NamedUpdate) SetNamespace(v string) *NamedUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableNamespace(v *string) *NamedUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *NamedUpdate) ClearNamespace() *NamedUpdate {
	_u.mutation.ClearNamespace()
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *NamedUpdate) SetAPIVersion(v string) *NamedUpdate {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableAPIVersion(v *string) *NamedUpdate {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NamedUpdate) SetKind(v string) *NamedUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableKind(v *string) *NamedUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NamedUpdate) SetUpdatedAt(v time.Time) *NamedUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *NamedUpdate) SetResourceVersion(v string) *NamedUpdate {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableResourceVersion(v *string) *NamedUpdate {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetSpecData sets the "spec_data" field.
func (_u *NamedUpdate) SetSpecData(v json.RawMessage) *NamedUpdate {
	_u.mutation.SetSpecData(v)
	return _u
}

// AppendSpecData appends value to the "spec_data" field.
func (_u *NamedUpdate) AppendSpecData(v json.RawMessage) *NamedUpdate {
	_u.mutation.AppendSpecData(v)
	return _u
}

// ClearSpecData clears the value of the "spec_data" field.
func (_u *NamedUpdate) ClearSpecData() *NamedUpdate {
	_u.mutation.ClearSpecData()
	return _u
}

// SetSpecName sets the "spec_name" field.
func (_u *NamedUpdate) SetSpecName(v string) *NamedUpdate {
	_u.mutation.SetSpecName(v)
	return _u
}

// SetNillableSpecName sets the "spec_name" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableSpecName(v *string) *NamedUpdate {
	if v != nil {
		_u.SetSpecName(*v)
	}
	return _u
}

// ClearSpecName clears the value of the "spec_name" field.
func (_u *NamedUpdate) ClearSpecName() *NamedUpdate {
	_u.mutation.ClearSpecName()
	return _u
}

// SetSpecAltName sets the "spec_alt_name" field.
func (_u *NamedUpdate) SetSpecAltName(v string) *NamedUpdate {
	_u.mutation.SetSpecAltName(v)
	return _u
}

// SetNillableSpecAltName sets the "spec_alt_name" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableSpecAltName(v *string) *NamedUpdate {
	if v != nil {
		_u.SetSpecAltName(*v)
	}
	return _u
}

// SetSpecNumber sets the "spec_number" field.
func (_u *NamedUpdate) SetSpecNumber(v int) *NamedUpdate {
	_u.mutation.ResetSpecNumber()
	_u.mutation.SetSpecNumber(v)
	return _u
}

// SetNillableSpecNumber sets the "spec_number" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableSpecNumber(v *int) *NamedUpdate {
	if v != nil {
		_u.SetSpecNumber(*v)
	}
	return _u
}

// AddSpecNumber adds value to the "spec_number" field.
func (_u *NamedUpdate) AddSpecNumber(v int) *NamedUpdate {
	_u.mutation.AddSpecNumber(v)
	return _u
}

// ClearSpecNumber clears the value of the "spec_number" field.
func (_u *NamedUpdate) ClearSpecNumber() *NamedUpdate {
	_u.mutation.ClearSpecNumber()
	return _u
}

// SetSpecSomethingOrNothing sets the "spec_something_or_nothing" field.
func (_u *NamedUpdate) SetSpecSomethingOrNothing(v string) *NamedUpdate {
	_u.mutation.SetSpecSomethingOrNothing(v)
	return _u
}

// SetNillableSpecSomethingOrNothing sets the "spec_something_or_nothing" field if the given value is not nil.
func (_u *NamedUpdate) SetNillableSpecSomethingOrNothing(v *string) *NamedUpdate {
	if v != nil {
		_u.SetSpecSomethingOrNothing(*v)
	}
	return _u
}

// ClearSpecSomethingOrNothing clears the value of the "spec_something_or_nothing" field.
func (_u *NamedUpdate) ClearSpecSomethingOrNothing() *NamedUpdate {
	_u.mutation.ClearSpecSomethingOrNothing()
	return _u
}

// Mutation returns the NamedMutation object of the builder.
func (_u *NamedUpdate) Mutation() *NamedMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NamedUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NamedUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NamedUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NamedUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NamedUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := named.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NamedUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := named.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Named.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecAltName(); ok {
		if err := named.SpecAltNameValidator(v); err != nil {
			return &ValidationError{Name: "spec_alt_name", err: fmt.Errorf(`ent: validator failed for field "Named.spec_alt_name": %w`, err)}
		}
	}
	return nil
}

func (_u *NamedUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(named.Table, named.Columns, sqlgraph.NewFieldSpec(named.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(named.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(named.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(named.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(named.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(named.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(named.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(named.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecData(); ok {
		_spec.SetField(named.FieldSpecData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, named.FieldSpecData, value)
		})
	}
	if _u.mutation.SpecDataCleared() {
		_spec.ClearField(named.FieldSpecData, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpecName(); ok {
		_spec.SetField(named.FieldSpecName, field.TypeString, value)
	}
	if _u.mutation.SpecNameCleared() {
		_spec.ClearField(named.FieldSpecName, field.TypeString)
	}
	if value, ok := _u.mutation.SpecAltName(); ok {
		_spec.SetField(named.FieldSpecAltName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecNumber(); ok {
		_spec.SetField(named.FieldSpecNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSpecNumber(); ok {
		_spec.AddField(named.FieldSpecNumber, field.TypeInt, value)
	}
	if _u.mutation.SpecNumberCleared() {
		_spec.ClearField(named.FieldSpecNumber, field.TypeInt)
	}
	if value, ok := _u.mutation.SpecSomethingOrNothing(); ok {
		_spec.SetField(named.FieldSpecSomethingOrNothing, field.TypeString, value)
	}
	if _u.mutation.SpecSomethingOrNothingCleared() {
		_spec.ClearField(named.FieldSpecSomethingOrNothing, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{named.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NamedUpdateOne is the builder for updating a single Named entity.
type NamedUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NamedMutation
}

// SetName sets the "name" field.
func (_u *NamedUpdateOne) SetName(v string) *NamedUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableName(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *NamedUpdateOne) SetNamespace(v string) *NamedUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableNamespace(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *NamedUpdateOne) ClearNamespace() *NamedUpdateOne {
	_u.mutation.ClearNamespace()
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *NamedUpdateOne) SetAPIVersion(v string) *NamedUpdateOne {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableAPIVersion(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NamedUpdateOne) SetKind(v string) *NamedUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableKind(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NamedUpdateOne) SetUpdatedAt(v time.Time) *NamedUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *NamedUpdateOne) SetResourceVersion(v string) *NamedUpdateOne {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableResourceVersion(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetSpecData sets the "spec_data" field.
func (_u *NamedUpdateOne) SetSpecData(v json.RawMessage) *NamedUpdateOne {
	_u.mutation.SetSpecData(v)
	return _u
}

// AppendSpecData appends value to the "spec_data" field.
func (_u *NamedUpdateOne) AppendSpecData(v json.RawMessage) *NamedUpdateOne {
	_u.mutation.AppendSpecData(v)
	return _u
}

// ClearSpecData clears the value of the "spec_data" field.
func (_u *NamedUpdateOne) ClearSpecData() *NamedUpdateOne {
	_u.mutation.ClearSpecData()
	return _u
}

// SetSpecName sets the "spec_name" field.
func (_u *NamedUpdateOne) SetSpecName(v string) *NamedUpdateOne {
	_u.mutation.SetSpecName(v)
	return _u
}

// SetNillableSpecName sets the "spec_name" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableSpecName(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetSpecName(*v)
	}
	return _u
}

// ClearSpecName clears the value of the "spec_name" field.
func (_u *NamedUpdateOne) ClearSpecName() *NamedUpdateOne {
	_u.mutation.ClearSpecName()
	return _u
}

// SetSpecAltName sets the "spec_alt_name" field.
func (_u *NamedUpdateOne) SetSpecAltName(v string) *NamedUpdateOne {
	_u.mutation.SetSpecAltName(v)
	return _u
}

// SetNillableSpecAltName sets the "spec_alt_name" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableSpecAltName(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetSpecAltName(*v)
	}
	return _u
}

// SetSpecNumber sets the "spec_number" field.
func (_u *NamedUpdateOne) SetSpecNumber(v int) *NamedUpdateOne {
	_u.mutation.ResetSpecNumber()
	_u.mutation.SetSpecNumber(v)
	return _u
}

// SetNillableSpecNumber sets the "spec_number" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableSpecNumber(v *int) *NamedUpdateOne {
	if v != nil {
		_u.SetSpecNumber(*v)
	}
	return _u
}

// AddSpecNumber adds value to the "spec_number" field.
func (_u *NamedUpdateOne) AddSpecNumber(v int) *NamedUpdateOne {
	_u.mutation.AddSpecNumber(v)
	return _u
}

// ClearSpecNumber clears the value of the "spec_number" field.
func (_u *NamedUpdateOne) ClearSpecNumber() *NamedUpdateOne {
	_u.mutation.ClearSpecNumber()
	return _u
}

// SetSpecSomethingOrNothing sets the "spec_something_or_nothing" field.
func (_u *NamedUpdateOne) SetSpecSomethingOrNothing(v string) *NamedUpdateOne {
	_u.mutation.SetSpecSomethingOrNothing(v)
	return _u
}

// SetNillableSpecSomethingOrNothing sets the "spec_something_or_nothing" field if the given value is not nil.
func (_u *NamedUpdateOne) SetNillableSpecSomethingOrNothing(v *string) *NamedUpdateOne {
	if v != nil {
		_u.SetSpecSomethingOrNothing(*v)
	}
	return _u
}

// ClearSpecSomethingOrNothing clears the value of the "spec_something_or_nothing" field.
func (_u *NamedUpdateOne) ClearSpecSomethingOrNothing() *NamedUpdateOne {
	_u.mutation.ClearSpecSomethingOrNothing()
	return _u
}

// Mutation returns the NamedMutation object of the builder.
func (_u *NamedUpdateOne) Mutation() *NamedMutation {
	return _u.mutation
}

// Where appends a list predicates to the NamedUpdate builder.
func (_u *NamedUpdateOne) Where(ps ...predicate.Named) *NamedUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NamedUpdateOne) Select(field string, fields ...string) *NamedUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Named entity.
func (_u *NamedUpdateOne) Save(ctx context.Context) (*Named, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NamedUpdateOne) SaveX(ctx context.Context) *Named {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NamedUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NamedUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NamedUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := named.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NamedUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := named.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Named.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SpecAltName(); ok {
		if err := named.SpecAltNameValidator(v); err != nil {
			return &ValidationError{Name: "spec_alt_name", err: fmt.Errorf(`ent: validator failed for field "Named.spec_alt_name": %w`, err)}
		}
	}
	return nil
}

func (_u *NamedUpdateOne) sqlSave(ctx context.Context) (_node *Named, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(named.Table, named.Columns, sqlgraph.NewFieldSpec(named.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Named.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, named.FieldID)
		for _, f := range fields {
			if !named.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != named.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(named.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(named.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(named.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(named.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(named.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(named.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(named.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecData(); ok {
		_spec.SetField(named.FieldSpecData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, named.FieldSpecData, value)
		})
	}
	if _u.mutation.SpecDataCleared() {
		_spec.ClearField(named.FieldSpecData, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpecName(); ok {
		_spec.SetField(named.FieldSpecName, field.TypeString, value)
	}
	if _u.mutation.SpecNameCleared() {
		_spec.ClearField(named.FieldSpecName, field.TypeString)
	}
	if value, ok := _u.mutation.SpecAltName(); ok {
		_spec.SetField(named.FieldSpecAltName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecNumber(); ok {
		_spec.SetField(named.FieldSpecNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSpecNumber(); ok {
		_spec.AddField(named.FieldSpecNumber, field.TypeInt, value)
	}
	if _u.mutation.SpecNumberCleared() {
		_spec.ClearField(named.FieldSpecNumber, field.TypeInt)
	}
	if value, ok := _u.mutation.SpecSomethingOrNothing(); ok {
		_spec.SetField(named.FieldSpecSomethingOrNothing, field.TypeString, value)
	}
	if _u.mutation.SpecSomethingOrNothingCleared() {
		_spec.ClearField(named.FieldSpecSomethingOrNothing, field.TypeString)
	}
	_node = &Named{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{named.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
