// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/openchami/named-resource-service/internal/storage/ent/annotation"
	"github.com/openchami/named-resource-service/internal/storage/ent/label"
	"github.com/openchami/named-resource-service/internal/storage/ent/named"
	"github.com/openchami/named-resource-service/internal/storage/ent/resource"
	"github.com/openchami/named-resource-service/internal/storage/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	annotationFields := schema.Annotation{}.Fields()
	_ = annotationFields
	// annotationDescKey is the schema descriptor for key field.
	annotationDescKey := annotationFields[0].Descriptor()
	// annotation.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	annotation.KeyValidator = func() func(string) error {
		validators := annotationDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	labelFields := schema.Label{}.Fields()
	_ = labelFields
	// labelDescKey is the schema descriptor for key field.
	labelDescKey := labelFields[0].Descriptor()
	// label.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	label.KeyValidator = func() func(string) error {
		validators := labelDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// labelDescValue is the schema descriptor for value field.
	labelDescValue := labelFields[1].Descriptor()
	// label.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	label.ValueValidator = labelDescValue.Validators[0].(func(string) error)
	namedFields := schema.Named{}.Fields()
	_ = namedFields
	// namedDescUID is the schema descriptor for uid field.
	namedDescUID := namedFields[0].Descriptor()
	// named.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	named.UIDValidator = namedDescUID.Validators[0].(func(string) error)
	// namedDescName is the schema descriptor for name field.
	namedDescName := namedFields[1].Descriptor()
	// named.NameValidator is a validator for the "name" field. It is called by the builders before save.
	named.NameValidator = func() func(string) error {
		validators := namedDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// namedDescAPIVersion is the schema descriptor for api_version field.
	namedDescAPIVersion := namedFields[3].Descriptor()
	// named.DefaultAPIVersion holds the default value on creation for the api_version field.
	named.DefaultAPIVersion = namedDescAPIVersion.Default.(string)
	// namedDescKind is the schema descriptor for kind field.
	namedDescKind := namedFields[4].Descriptor()
	// named.DefaultKind holds the default value on creation for the kind field.
	named.DefaultKind = namedDescKind.Default.(string)
	// namedDescCreatedAt is the schema descriptor for created_at field.
	namedDescCreatedAt := namedFields[5].Descriptor()
	// named.DefaultCreatedAt holds the default value on creation for the created_at field.
	named.DefaultCreatedAt = namedDescCreatedAt.Default.(func() time.Time)
	// namedDescUpdatedAt is the schema descriptor for updated_at field.
	namedDescUpdatedAt := namedFields[6].Descriptor()
	// named.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	named.DefaultUpdatedAt = namedDescUpdatedAt.Default.(func() time.Time)
	// named.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	named.UpdateDefaultUpdatedAt = namedDescUpdatedAt.UpdateDefault.(func() time.Time)
	// namedDescResourceVersion is the schema descriptor for resource_version field.
	namedDescResourceVersion := namedFields[7].Descriptor()
	// named.DefaultResourceVersion holds the default value on creation for the resource_version field.
	named.DefaultResourceVersion = namedDescResourceVersion.Default.(string)
	// namedDescSpecAltName is the schema descriptor for spec_alt_name field.
	namedDescSpecAltName := namedFields[10].Descriptor()
	// named.SpecAltNameValidator is a validator for the "spec_alt_name" field. It is called by the builders before save.
	named.SpecAltNameValidator = func() func(string) error {
		validators := namedDescSpecAltName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(spec_alt_name string) error {
			for _, fn := range fns {
				if err := fn(spec_alt_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// namedDescSpecNumber is the schema descriptor for spec_number field.
	namedDescSpecNumber := namedFields[11].Descriptor()
	// named.DefaultSpecNumber holds the default value on creation for the spec_number field.
	named.DefaultSpecNumber = namedDescSpecNumber.Default.(int)
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescUID is the schema descriptor for uid field.
	resourceDescUID := resourceFields[0].Descriptor()
	// resource.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	resource.UIDValidator = resourceDescUID.Validators[0].(func(string) error)
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[1].Descriptor()
	// resource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resource.NameValidator = func() func(string) error {
		validators := resourceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescAPIVersion is the schema descriptor for api_version field.
	resourceDescAPIVersion := resourceFields[2].Descriptor()
	// resource.DefaultAPIVersion holds the default value on creation for the api_version field.
	resource.DefaultAPIVersion = resourceDescAPIVersion.Default.(string)
	// resourceDescKind is the schema descriptor for kind field.
	resourceDescKind := resourceFields[3].Descriptor()
	// resource.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	resource.KindValidator = resourceDescKind.Validators[0].(func(string) error)
	// resourceDescResourceType is the schema descriptor for resource_type field.
	resourceDescResourceType := resourceFields[4].Descriptor()
	// resource.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	resource.ResourceTypeValidator = resourceDescResourceType.Validators[0].(func(string) error)
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceFields[7].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceFields[8].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourceDescResourceVersion is the schema descriptor for resource_version field.
	resourceDescResourceVersion := resourceFields[9].Descriptor()
	// resource.DefaultResourceVersion holds the default value on creation for the resource_version field.
	resource.DefaultResourceVersion = resourceDescResourceVersion.Default.(string)
}
