// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the node_service_sqlite API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//   1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//   2. Run 'make generate-client-cmd' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client health
//   - client node [list|get|create|update|patch|delete]
//
// Global flags (available for all commands):
//   --server       Server URL (env: NODE_SERVICE_SQLITE_SERVER)
//   --timeout      Request timeout (env: NODE_SERVICE_SQLITE_TIMEOUT)
//   --output, -o   Output format: table, json, yaml (env: NODE_SERVICE_SQLITE_OUTPUT)
//   --version, -v  API version to request: v1, v2beta1, etc. (env: NODE_SERVICE_SQLITE_VERSION)
//   --token        JWT bearer token (env: NODE_SERVICE_SQLITE_TOKEN)
//   --show-token   Show the full bearer token in debug logs
//   --config       Config file path (default: ~/.node_service_sqlite-cli.yaml)
//
// Configuration sources (in order of precedence):
//   1. Command-line flags
//   2. Environment variables (NODE_SERVICE_SQLITE_*)
//   3. Config file (~/.node_service_sqlite-cli.yaml)
//   4. Default values
//
// Usage examples:
//   # List all nodes (default version)
//   client node list
//
//   # List nodes with specific version
//   client node list --version v2beta1
//
//   # Get Node as v1
//   client node get <uid> --version v1
//
//   # Create from JSON file with version
//   cat node.json | client node create --version v2beta1
//
//   # Create from inline JSON
//   client node create --spec '{"name":"node-01","description":"Example Node"}'
//
//   # Use environment variables
//   export NODE_SERVICE_SQLITE_SERVER=https://node_service_sqlite.example.com
//   export NODE_SERVICE_SQLITE_VERSION=v2beta1
//   client node list
//
// To add custom commands:
//   1. Add command definition in template after resource commands
//   2. Register it in init() function
//
// To change output formatting:
//   1. Modify printOutput function to add new formats
//   2. Update output flag validation
//
// To add authentication:
//   1. Add auth flags (--token, --username, etc.)
//   2. Modify getClient to configure auth in http.Client
//   3. Add auth headers in client package
//
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/openchami/node-service-sqlite/pkg/client"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	cfgFile     string
	serverURL   string
	timeout     time.Duration
	output      string
	apiVersion  string
	bearerToken string
	showToken   bool
	logLevel    client.LogLevel
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "node_service_sqlite CLI",
	Long:  `A command-line interface for managing node_service_sqlite resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.node_service_sqlite-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "node_service_sqlite server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")
	rootCmd.PersistentFlags().StringVar(&bearerToken, "token", "", "JWT bearer token")
	rootCmd.PersistentFlags().BoolVar(&showToken, "show-token", false, "show full bearer token in debug logs instead of a truncated value")
	rootCmd.PersistentFlags().VarP(&logLevel, "log-level", "l", "set verbosity of logs (e.g., info, warning, debug)")

	// Register shell completion functions
	rootCmd.RegisterFlagCompletionFunc("log-level", client.CompletionLogLevel)

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))
	viper.BindPFlag("token", rootCmd.PersistentFlags().Lookup("token"))
	viper.BindPFlag("show-token", rootCmd.PersistentFlags().Lookup("show-token"))
	viper.BindPFlag("log-level", rootCmd.PersistentFlags().Lookup("log-level"))

	// Environment variable support
	viper.SetEnvPrefix("NODE_SERVICE_SQLITE")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(healthCmd)
	rootCmd.AddCommand(NewVersionCommand())
	rootCmd.AddCommand(nodeCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".node_service_sqlite-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	// Error will cause default logger, which is handled by NewClient()
	logger, _ := client.NewLogger(logLevel)
	c, err := client.NewClient(serverURL, nil, logger)
	if err != nil {
		return nil, err
	}
	c = c.WithShowToken(viper.GetBool("show-token"))

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	token := viper.GetString("token")
	if token != "" {
		c = c.WithBearerToken(token)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

var healthCmd = &cobra.Command{
	Use:   "health",
	Short: "Get service health status",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		health, err := c.GetHealth(ctx)
		if err != nil {
			return fmt.Errorf("failed to get health status: %w", err)
		}

		return printOutput(health)
	},
}

// setNestedField sets a field in a nested map using dot notation
// Example: setNestedField(map, "status.health", "OK") sets map["status"]["health"] = "OK"
func setNestedField(target map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := target

	// Navigate to the parent of the target field
	for _, part := range parts[:len(parts)-1] {
		if current[part] == nil {
			current[part] = make(map[string]interface{})
		}
		if nested, ok := current[part].(map[string]interface{}); ok {
			current = nested
		} else {
			// Convert to map if it's not already
			current[part] = make(map[string]interface{})
			current = current[part].(map[string]interface{})
		}
	}

	// Set the final field
	finalField := parts[len(parts)-1]
	if value == nil {
		// For unset operations, we use JSON Merge Patch null semantics
		current[finalField] = nil
	} else if stringValue, ok := value.(string); ok {
		// Try to parse as JSON first, then as string
		var jsonValue interface{}
		if err := json.Unmarshal([]byte(stringValue), &jsonValue); err == nil {
			current[finalField] = jsonValue
		} else {
			current[finalField] = stringValue
		}
	} else {
		current[finalField] = value
	}
}

// Node commands
var nodeCmd = &cobra.Command{
	Use:   "node",
	Short: "Manage nodes",
	Long:  `Create, read, update, patch, and delete nodes.`,
}

var nodeListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all nodes",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetNodes(ctx)
		if err != nil {
			return fmt.Errorf("failed to list nodes: %w", err)
		}

		return printOutput(items)
	},
}

var nodeGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a Node by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetNode(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new Node",
	Long: `Create a new Node.

Examples:
  # Create from stdin
  echo '{"id": "example-value", "number": 42, "somethingOrNothing": "example-value"}' | client node create

  # Create with --spec flag
  client node create --spec '{"id": "example-value", "number": 42, "somethingOrNothing": "example-value"}'

Spec fields:
  id (string)
  number (int)
  somethingOrNothing (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateNode(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing Node",
	Long: `Update an existing Node.

Examples:
  # Update from stdin
  echo '{"id": "example-value", "number": 42, "somethingOrNothing": "example-value"}' | client node update <uid>

  # Update with --spec flag
  client node update <uid> --spec '{"id": "example-value", "number": 42, "somethingOrNothing": "example-value"}'

Spec fields:
  id (string)
  number (int)
  somethingOrNothing (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateNode(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodePatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a Node",
	Long: `Patch an existing Node spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client node patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client node patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client node patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client node patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchNode(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeDeleteCmd = &cobra.Command{
	Use:   "delete [uid...]",
	Short: "Delete one or more Node resources",
	Long: `Deletes one or more Node resources.

You can provide multiple UIDs separated by spaces to delete them all in a single command.
Each UID is processed one by one as an individual, atomic delete operation. If any deletion fails, the command will still attempt to delete the remaining UIDs and report the errors at the end.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		var errs []error
		for _, uid := range args {
			if err := c.DeleteNode(ctx, uid); err != nil {
				errs = append(errs, fmt.Errorf("failed to delete Node %q: %w", uid, err))
				continue
			}
			fmt.Printf("Node %s deleted successfully\n", uid)
		}

		if len(errs) > 0 {
			var errMsgs []string
			for _, e := range errs {
				errMsgs = append(errMsgs, e.Error())
			}
			return fmt.Errorf("encountered %d error(s) during deletion:\n%s", len(errs), strings.Join(errMsgs, "\n"))
		}
		return nil
	},
}

func init() {
	nodeCmd.AddCommand(nodeListCmd)
	nodeCmd.AddCommand(nodeGetCmd)
	nodeCmd.AddCommand(nodeCreateCmd)
	nodeCmd.AddCommand(nodeUpdateCmd)
	nodeCmd.AddCommand(nodePatchCmd)
	nodeCmd.AddCommand(nodeDeleteCmd)

	// Add spec flag for create and update commands
	nodeCreateCmd.Flags().String("spec", "", "Node specification in JSON format")
	nodeUpdateCmd.Flags().String("spec", "", "Node specification in JSON format")

	// Add patch command flags
	nodePatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	nodePatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	nodePatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	nodePatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	nodePatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	nodePatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}
