// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openchami/user-service/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNamespace, v))
}

// APIVersion applies equality check predicate on the "api_version" field. It's identical to APIVersionEQ.
func APIVersion(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAPIVersion, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldKind, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// ResourceVersion applies equality check predicate on the "resource_version" field. It's identical to ResourceVersionEQ.
func ResourceVersion(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldResourceVersion, v))
}

// SpecUsername applies equality check predicate on the "spec_username" field. It's identical to SpecUsernameEQ.
func SpecUsername(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecUsername, v))
}

// SpecEmail applies equality check predicate on the "spec_email" field. It's identical to SpecEmailEQ.
func SpecEmail(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecEmail, v))
}

// SpecPassword applies equality check predicate on the "spec_password" field. It's identical to SpecPasswordEQ.
func SpecPassword(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecPassword, v))
}

// SpecRole applies equality check predicate on the "spec_role" field. It's identical to SpecRoleEQ.
func SpecRole(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecRole, v))
}

// SpecActive applies equality check predicate on the "spec_active" field. It's identical to SpecActiveEQ.
func SpecActive(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecActive, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceIsNil applies the IsNil predicate on the "namespace" field.
func NamespaceIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldNamespace))
}

// NamespaceNotNil applies the NotNil predicate on the "namespace" field.
func NamespaceNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldNamespace))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldNamespace, v))
}

// APIVersionEQ applies the EQ predicate on the "api_version" field.
func APIVersionEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAPIVersion, v))
}

// APIVersionNEQ applies the NEQ predicate on the "api_version" field.
func APIVersionNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAPIVersion, v))
}

// APIVersionIn applies the In predicate on the "api_version" field.
func APIVersionIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAPIVersion, vs...))
}

// APIVersionNotIn applies the NotIn predicate on the "api_version" field.
func APIVersionNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAPIVersion, vs...))
}

// APIVersionGT applies the GT predicate on the "api_version" field.
func APIVersionGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAPIVersion, v))
}

// APIVersionGTE applies the GTE predicate on the "api_version" field.
func APIVersionGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAPIVersion, v))
}

// APIVersionLT applies the LT predicate on the "api_version" field.
func APIVersionLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAPIVersion, v))
}

// APIVersionLTE applies the LTE predicate on the "api_version" field.
func APIVersionLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAPIVersion, v))
}

// APIVersionContains applies the Contains predicate on the "api_version" field.
func APIVersionContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAPIVersion, v))
}

// APIVersionHasPrefix applies the HasPrefix predicate on the "api_version" field.
func APIVersionHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAPIVersion, v))
}

// APIVersionHasSuffix applies the HasSuffix predicate on the "api_version" field.
func APIVersionHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAPIVersion, v))
}

// APIVersionEqualFold applies the EqualFold predicate on the "api_version" field.
func APIVersionEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAPIVersion, v))
}

// APIVersionContainsFold applies the ContainsFold predicate on the "api_version" field.
func APIVersionContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAPIVersion, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldKind, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// ResourceVersionEQ applies the EQ predicate on the "resource_version" field.
func ResourceVersionEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldResourceVersion, v))
}

// ResourceVersionNEQ applies the NEQ predicate on the "resource_version" field.
func ResourceVersionNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldResourceVersion, v))
}

// ResourceVersionIn applies the In predicate on the "resource_version" field.
func ResourceVersionIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldResourceVersion, vs...))
}

// ResourceVersionNotIn applies the NotIn predicate on the "resource_version" field.
func ResourceVersionNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldResourceVersion, vs...))
}

// ResourceVersionGT applies the GT predicate on the "resource_version" field.
func ResourceVersionGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldResourceVersion, v))
}

// ResourceVersionGTE applies the GTE predicate on the "resource_version" field.
func ResourceVersionGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldResourceVersion, v))
}

// ResourceVersionLT applies the LT predicate on the "resource_version" field.
func ResourceVersionLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldResourceVersion, v))
}

// ResourceVersionLTE applies the LTE predicate on the "resource_version" field.
func ResourceVersionLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldResourceVersion, v))
}

// ResourceVersionContains applies the Contains predicate on the "resource_version" field.
func ResourceVersionContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldResourceVersion, v))
}

// ResourceVersionHasPrefix applies the HasPrefix predicate on the "resource_version" field.
func ResourceVersionHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldResourceVersion, v))
}

// ResourceVersionHasSuffix applies the HasSuffix predicate on the "resource_version" field.
func ResourceVersionHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldResourceVersion, v))
}

// ResourceVersionEqualFold applies the EqualFold predicate on the "resource_version" field.
func ResourceVersionEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldResourceVersion, v))
}

// ResourceVersionContainsFold applies the ContainsFold predicate on the "resource_version" field.
func ResourceVersionContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldResourceVersion, v))
}

// SpecDataIsNil applies the IsNil predicate on the "spec_data" field.
func SpecDataIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecData))
}

// SpecDataNotNil applies the NotNil predicate on the "spec_data" field.
func SpecDataNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecData))
}

// SpecUsernameEQ applies the EQ predicate on the "spec_username" field.
func SpecUsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecUsername, v))
}

// SpecUsernameNEQ applies the NEQ predicate on the "spec_username" field.
func SpecUsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSpecUsername, v))
}

// SpecUsernameIn applies the In predicate on the "spec_username" field.
func SpecUsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSpecUsername, vs...))
}

// SpecUsernameNotIn applies the NotIn predicate on the "spec_username" field.
func SpecUsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSpecUsername, vs...))
}

// SpecUsernameGT applies the GT predicate on the "spec_username" field.
func SpecUsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSpecUsername, v))
}

// SpecUsernameGTE applies the GTE predicate on the "spec_username" field.
func SpecUsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSpecUsername, v))
}

// SpecUsernameLT applies the LT predicate on the "spec_username" field.
func SpecUsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSpecUsername, v))
}

// SpecUsernameLTE applies the LTE predicate on the "spec_username" field.
func SpecUsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSpecUsername, v))
}

// SpecUsernameContains applies the Contains predicate on the "spec_username" field.
func SpecUsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSpecUsername, v))
}

// SpecUsernameHasPrefix applies the HasPrefix predicate on the "spec_username" field.
func SpecUsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSpecUsername, v))
}

// SpecUsernameHasSuffix applies the HasSuffix predicate on the "spec_username" field.
func SpecUsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSpecUsername, v))
}

// SpecUsernameIsNil applies the IsNil predicate on the "spec_username" field.
func SpecUsernameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecUsername))
}

// SpecUsernameNotNil applies the NotNil predicate on the "spec_username" field.
func SpecUsernameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecUsername))
}

// SpecUsernameEqualFold applies the EqualFold predicate on the "spec_username" field.
func SpecUsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSpecUsername, v))
}

// SpecUsernameContainsFold applies the ContainsFold predicate on the "spec_username" field.
func SpecUsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSpecUsername, v))
}

// SpecEmailEQ applies the EQ predicate on the "spec_email" field.
func SpecEmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecEmail, v))
}

// SpecEmailNEQ applies the NEQ predicate on the "spec_email" field.
func SpecEmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSpecEmail, v))
}

// SpecEmailIn applies the In predicate on the "spec_email" field.
func SpecEmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSpecEmail, vs...))
}

// SpecEmailNotIn applies the NotIn predicate on the "spec_email" field.
func SpecEmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSpecEmail, vs...))
}

// SpecEmailGT applies the GT predicate on the "spec_email" field.
func SpecEmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSpecEmail, v))
}

// SpecEmailGTE applies the GTE predicate on the "spec_email" field.
func SpecEmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSpecEmail, v))
}

// SpecEmailLT applies the LT predicate on the "spec_email" field.
func SpecEmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSpecEmail, v))
}

// SpecEmailLTE applies the LTE predicate on the "spec_email" field.
func SpecEmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSpecEmail, v))
}

// SpecEmailContains applies the Contains predicate on the "spec_email" field.
func SpecEmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSpecEmail, v))
}

// SpecEmailHasPrefix applies the HasPrefix predicate on the "spec_email" field.
func SpecEmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSpecEmail, v))
}

// SpecEmailHasSuffix applies the HasSuffix predicate on the "spec_email" field.
func SpecEmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSpecEmail, v))
}

// SpecEmailIsNil applies the IsNil predicate on the "spec_email" field.
func SpecEmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecEmail))
}

// SpecEmailNotNil applies the NotNil predicate on the "spec_email" field.
func SpecEmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecEmail))
}

// SpecEmailEqualFold applies the EqualFold predicate on the "spec_email" field.
func SpecEmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSpecEmail, v))
}

// SpecEmailContainsFold applies the ContainsFold predicate on the "spec_email" field.
func SpecEmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSpecEmail, v))
}

// SpecPasswordEQ applies the EQ predicate on the "spec_password" field.
func SpecPasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecPassword, v))
}

// SpecPasswordNEQ applies the NEQ predicate on the "spec_password" field.
func SpecPasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSpecPassword, v))
}

// SpecPasswordIn applies the In predicate on the "spec_password" field.
func SpecPasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSpecPassword, vs...))
}

// SpecPasswordNotIn applies the NotIn predicate on the "spec_password" field.
func SpecPasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSpecPassword, vs...))
}

// SpecPasswordGT applies the GT predicate on the "spec_password" field.
func SpecPasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSpecPassword, v))
}

// SpecPasswordGTE applies the GTE predicate on the "spec_password" field.
func SpecPasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSpecPassword, v))
}

// SpecPasswordLT applies the LT predicate on the "spec_password" field.
func SpecPasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSpecPassword, v))
}

// SpecPasswordLTE applies the LTE predicate on the "spec_password" field.
func SpecPasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSpecPassword, v))
}

// SpecPasswordContains applies the Contains predicate on the "spec_password" field.
func SpecPasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSpecPassword, v))
}

// SpecPasswordHasPrefix applies the HasPrefix predicate on the "spec_password" field.
func SpecPasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSpecPassword, v))
}

// SpecPasswordHasSuffix applies the HasSuffix predicate on the "spec_password" field.
func SpecPasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSpecPassword, v))
}

// SpecPasswordIsNil applies the IsNil predicate on the "spec_password" field.
func SpecPasswordIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecPassword))
}

// SpecPasswordNotNil applies the NotNil predicate on the "spec_password" field.
func SpecPasswordNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecPassword))
}

// SpecPasswordEqualFold applies the EqualFold predicate on the "spec_password" field.
func SpecPasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSpecPassword, v))
}

// SpecPasswordContainsFold applies the ContainsFold predicate on the "spec_password" field.
func SpecPasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSpecPassword, v))
}

// SpecRoleEQ applies the EQ predicate on the "spec_role" field.
func SpecRoleEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecRole, v))
}

// SpecRoleNEQ applies the NEQ predicate on the "spec_role" field.
func SpecRoleNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSpecRole, v))
}

// SpecRoleIn applies the In predicate on the "spec_role" field.
func SpecRoleIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSpecRole, vs...))
}

// SpecRoleNotIn applies the NotIn predicate on the "spec_role" field.
func SpecRoleNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSpecRole, vs...))
}

// SpecRoleGT applies the GT predicate on the "spec_role" field.
func SpecRoleGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSpecRole, v))
}

// SpecRoleGTE applies the GTE predicate on the "spec_role" field.
func SpecRoleGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSpecRole, v))
}

// SpecRoleLT applies the LT predicate on the "spec_role" field.
func SpecRoleLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSpecRole, v))
}

// SpecRoleLTE applies the LTE predicate on the "spec_role" field.
func SpecRoleLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSpecRole, v))
}

// SpecRoleContains applies the Contains predicate on the "spec_role" field.
func SpecRoleContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSpecRole, v))
}

// SpecRoleHasPrefix applies the HasPrefix predicate on the "spec_role" field.
func SpecRoleHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSpecRole, v))
}

// SpecRoleHasSuffix applies the HasSuffix predicate on the "spec_role" field.
func SpecRoleHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSpecRole, v))
}

// SpecRoleIsNil applies the IsNil predicate on the "spec_role" field.
func SpecRoleIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecRole))
}

// SpecRoleNotNil applies the NotNil predicate on the "spec_role" field.
func SpecRoleNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecRole))
}

// SpecRoleEqualFold applies the EqualFold predicate on the "spec_role" field.
func SpecRoleEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSpecRole, v))
}

// SpecRoleContainsFold applies the ContainsFold predicate on the "spec_role" field.
func SpecRoleContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSpecRole, v))
}

// SpecActiveEQ applies the EQ predicate on the "spec_active" field.
func SpecActiveEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSpecActive, v))
}

// SpecActiveNEQ applies the NEQ predicate on the "spec_active" field.
func SpecActiveNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSpecActive, v))
}

// SpecActiveIsNil applies the IsNil predicate on the "spec_active" field.
func SpecActiveIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSpecActive))
}

// SpecActiveNotNil applies the NotNil predicate on the "spec_active" field.
func SpecActiveNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSpecActive))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
