// Code generated by Fabrica dev. DO NOT EDIT.
// Template: client/version.go.tmpl
// Generated: 2026-08-26T03:43:00Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// Client version information - set via ldflags at build time
var (
	clientVersion = "dev"
	clientCommit  = "none"
	clientDate    = "unknown"
)

// fabricaVersion is embedded at generation time
const fabricaVersion = "dev"

func clientVersionString() string {
	if clientCommit == "none" && clientDate == "unknown" {
		return clientVersion
	}
	if clientCommit == "none" {
		return fmt.Sprintf("%s (built: %s)", clientVersion, clientDate)
	}
	if clientDate == "unknown" {
		return fmt.Sprintf("%s (commit: %s)", clientVersion, clientCommit)
	}
	return fmt.Sprintf("%s (commit: %s, built: %s)", clientVersion, clientCommit, clientDate)
}

// NewVersionCommand creates the version command for the CLI client
func NewVersionCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version information",
		Long:  `Print version information for user_service CLI client`,
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("user_service CLI version %s\n", clientVersion)
			if clientCommit != "none" {
				fmt.Printf("  commit: %s\n", clientCommit)
			}
			if clientDate != "unknown" {
				fmt.Printf("  built:  %s\n", clientDate)
			}
			fmt.Printf("  generated by: Fabrica %s\n", fabricaVersion)
		},
	}
}
