
// Code generated by Fabrica dev. DO NOT EDIT.
// Template: init/auth_helpers.go.tmpl
// Generated: 2026-08-28T18:16:44Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"net/http"
	
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	tokensmithauthn "github.com/openchami/tokensmith/pkg/authn"
	tokensmithauthz "github.com/openchami/tokensmith/pkg/authz"
	tokensmithauthzengine "github.com/openchami/tokensmith/pkg/authz/engine"
	
)

func initializeAuthMiddleware(config *Config) (func(http.Handler) http.Handler, func(http.Handler) http.Handler, error) {
	
	var authnMiddleware func(http.Handler) http.Handler
	var authzMiddleware func(http.Handler) http.Handler
	if config.AuthEnabled {
		jwksURL := os.Getenv("TOKENSMITH_JWKS_URL")
		if jwksURL == "" {
			return nil, nil, fmt.Errorf("TOKENSMITH_JWKS_URL is required when security.authn.enabled is true")
		}

		mw, err := tokensmithauthn.Middleware(tokensmithauthn.Options{
			JWKSURLs:                  []string{jwksURL},
			DisableIssuerValidation:   true,
			DisableAudienceValidation: true,
		})
		if err != nil {
			return nil, nil, fmt.Errorf("failed to initialize TokenSmith JWT middleware: %w", err)
		}
		authnMiddleware = mw
		log.Println("Authentication enabled (TokenSmith JWT)")

		authzMode, err := parseAuthZMode(os.Getenv("TOKENSMITH_AUTHZ_MODE"))
		if err != nil {
			return nil, nil, fmt.Errorf("failed to parse TOKENSMITH_AUTHZ_MODE: %w", err)
		}
		if authzMode != tokensmithauthz.ModeOff {
			modelPath := getenvDefault("TOKENSMITH_CASBIN_MODEL", "./authz/model.conf")
			policyPath := getenvDefault("TOKENSMITH_CASBIN_POLICY", "./authz/policy.csv")
			groupingPath := getenvDefault("TOKENSMITH_CASBIN_GROUPING", "./authz/grouping.csv")

			authorizer, err := tokensmithauthzengine.NewBuilder().
				WithModelPath(modelPath).
				WithPolicyPath(policyPath).
				WithGroupingPath(groupingPath).
				Build()
			if err != nil {
				return nil, nil, fmt.Errorf("failed to initialize TokenSmith AuthZ engine: %w", err)
			}

			authzMiddleware = tokensmithauthz.NewMiddleware(
				authorizer,
				authzRouteMapper{},
				tokensmithauthz.WithMode(authzMode),
				tokensmithauthz.WithRequireAuthn(true),
				tokensmithauthz.WithOnDecision(logAuthZDecision),
			).Handler
			log.Printf("Authorization enabled (TokenSmith AuthZ, mode=%s)", authzMode)
		} else {
			log.Println("Authorization disabled")
		}
	} else {
		log.Println("Authentication disabled")
	}

	return authnMiddleware, authzMiddleware, nil
	
}


func parseAuthZMode(s string) (tokensmithauthz.Mode, error) {
	switch strings.TrimSpace(strings.ToLower(s)) {
	case "", "off":
		return tokensmithauthz.ModeOff, nil
	case "shadow":
		return tokensmithauthz.ModeShadow, nil
	case "enforce":
		return tokensmithauthz.ModeEnforce, nil
	default:
		return tokensmithauthz.ModeOff, fmt.Errorf("unknown authz mode %q", s)
	}
}

func getenvDefault(key, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return fallback
}

func logAuthZDecision(_ context.Context, rec tokensmithauthz.DecisionRecord) {
	log.Printf(
		"authz decision subject=%q decision=%q reason=%q mode=%q object=%q action=%q method=%q path=%q request_id=%q policy_version=%q roles_count=%d",
		rec.PrincipalID,
		rec.Decision,
		rec.Reason,
		rec.Mode,
		rec.Object,
		rec.Action,
		rec.Method,
		rec.Path,
		rec.RequestID,
		rec.PolicyVersion,
		rec.RolesCount,
	)
}

