// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-08-26T05:02:15Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/user-service-postgres/apis/storage-annotations.openchami.org/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.User{}); err != nil {
		return fmt.Errorf("failed to register User: %w", err)
	}
	if err := applyResourceAnnotations(gen, "User", "apis\\storage-annotations.openchami.org\\v1"); err != nil {
		return err
	}

	return nil
}

// applyResourceAnnotations parses +fabrica: annotations for a resource from its
// source files in dir and attaches them to the generator. Files that do not
// declare the resource contribute nothing.
func applyResourceAnnotations(gen *codegen.Generator, name, dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		fileName := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(fileName, ".go") || strings.HasSuffix(fileName, "_test.go") {
			continue
		}
		annots, err := gen.ParseResourceAnnotations(filepath.Join(dir, fileName), name)
		if err != nil {
			return fmt.Errorf("parse annotations for %s: %w", name, err)
		}
		if annots == nil {
			continue
		}
		if annots.IsResource || annots.StorageMode == "dedicated" || len(annots.Fields) > 0 || len(annots.Indexes) > 0 {
			gen.SetResourceAnnotations(name, annots)
			return nil
		}
	}
	return nil
}
