// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/openchami/user-service/internal/storage/ent/annotation"
	"github.com/openchami/user-service/internal/storage/ent/label"
	"github.com/openchami/user-service/internal/storage/ent/resource"
	"github.com/openchami/user-service/internal/storage/ent/schema"
	"github.com/openchami/user-service/internal/storage/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	annotationFields := schema.Annotation{}.Fields()
	_ = annotationFields
	// annotationDescKey is the schema descriptor for key field.
	annotationDescKey := annotationFields[0].Descriptor()
	// annotation.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	annotation.KeyValidator = func() func(string) error {
		validators := annotationDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	labelFields := schema.Label{}.Fields()
	_ = labelFields
	// labelDescKey is the schema descriptor for key field.
	labelDescKey := labelFields[0].Descriptor()
	// label.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	label.KeyValidator = func() func(string) error {
		validators := labelDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// labelDescValue is the schema descriptor for value field.
	labelDescValue := labelFields[1].Descriptor()
	// label.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	label.ValueValidator = labelDescValue.Validators[0].(func(string) error)
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescUID is the schema descriptor for uid field.
	resourceDescUID := resourceFields[0].Descriptor()
	// resource.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	resource.UIDValidator = resourceDescUID.Validators[0].(func(string) error)
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[1].Descriptor()
	// resource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	resource.NameValidator = func() func(string) error {
		validators := resourceDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// resourceDescAPIVersion is the schema descriptor for api_version field.
	resourceDescAPIVersion := resourceFields[2].Descriptor()
	// resource.DefaultAPIVersion holds the default value on creation for the api_version field.
	resource.DefaultAPIVersion = resourceDescAPIVersion.Default.(string)
	// resourceDescKind is the schema descriptor for kind field.
	resourceDescKind := resourceFields[3].Descriptor()
	// resource.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	resource.KindValidator = resourceDescKind.Validators[0].(func(string) error)
	// resourceDescResourceType is the schema descriptor for resource_type field.
	resourceDescResourceType := resourceFields[4].Descriptor()
	// resource.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	resource.ResourceTypeValidator = resourceDescResourceType.Validators[0].(func(string) error)
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceFields[7].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceFields[8].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourceDescResourceVersion is the schema descriptor for resource_version field.
	resourceDescResourceVersion := resourceFields[9].Descriptor()
	// resource.DefaultResourceVersion holds the default value on creation for the resource_version field.
	resource.DefaultResourceVersion = resourceDescResourceVersion.Default.(string)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUID is the schema descriptor for uid field.
	userDescUID := userFields[0].Descriptor()
	// user.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	user.UIDValidator = userDescUID.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescAPIVersion is the schema descriptor for api_version field.
	userDescAPIVersion := userFields[3].Descriptor()
	// user.DefaultAPIVersion holds the default value on creation for the api_version field.
	user.DefaultAPIVersion = userDescAPIVersion.Default.(string)
	// userDescKind is the schema descriptor for kind field.
	userDescKind := userFields[4].Descriptor()
	// user.DefaultKind holds the default value on creation for the kind field.
	user.DefaultKind = userDescKind.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescResourceVersion is the schema descriptor for resource_version field.
	userDescResourceVersion := userFields[7].Descriptor()
	// user.DefaultResourceVersion holds the default value on creation for the resource_version field.
	user.DefaultResourceVersion = userDescResourceVersion.Default.(string)
	// userDescSpecRole is the schema descriptor for spec_role field.
	userDescSpecRole := userFields[12].Descriptor()
	// user.DefaultSpecRole holds the default value on creation for the spec_role field.
	user.DefaultSpecRole = userDescSpecRole.Default.(string)
	// userDescSpecActive is the schema descriptor for spec_active field.
	userDescSpecActive := userFields[13].Descriptor()
	// user.DefaultSpecActive holds the default value on creation for the spec_active field.
	user.DefaultSpecActive = userDescSpecActive.Default.(bool)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
