project:
    name: named-resource-service
    module: github.com/openchami/named-resource-service
    created: 2026-08-24T09:18:25.692655316-06:00
features:
    validation:
        enabled: true
        mode: strict
    events:
        enabled: false
        bus_type: memory
    conditional:
        enabled: true
        etag_algorithm: sha256
    auth:
        enabled: false
    storage:
        enabled: true
        type: ent
        db_driver: sqlite3
    reconciliation:
        enabled: false
        worker_count: 5
        requeue_delay: 5
generation:
    handlers: true
    storage: true
    client: true
    openapi: true
    events: false
    middleware: true
    reconciliation: false
