// Code generated by ent, DO NOT EDIT.

package named

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openchami/named-resource-service/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldID, id))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldUID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldName, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldNamespace, v))
}

// APIVersion applies equality check predicate on the "api_version" field. It's identical to APIVersionEQ.
func APIVersion(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldAPIVersion, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldKind, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldUpdatedAt, v))
}

// ResourceVersion applies equality check predicate on the "resource_version" field. It's identical to ResourceVersionEQ.
func ResourceVersion(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldResourceVersion, v))
}

// SpecName applies equality check predicate on the "spec_name" field. It's identical to SpecNameEQ.
func SpecName(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecName, v))
}

// SpecAltName applies equality check predicate on the "spec_alt_name" field. It's identical to SpecAltNameEQ.
func SpecAltName(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecAltName, v))
}

// SpecNumber applies equality check predicate on the "spec_number" field. It's identical to SpecNumberEQ.
func SpecNumber(v int) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecNumber, v))
}

// SpecSomethingOrNothing applies equality check predicate on the "spec_something_or_nothing" field. It's identical to SpecSomethingOrNothingEQ.
func SpecSomethingOrNothing(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecSomethingOrNothing, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldUID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldName, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceIsNil applies the IsNil predicate on the "namespace" field.
func NamespaceIsNil() predicate.Named {
	return predicate.Named(sql.FieldIsNull(FieldNamespace))
}

// NamespaceNotNil applies the NotNil predicate on the "namespace" field.
func NamespaceNotNil() predicate.Named {
	return predicate.Named(sql.FieldNotNull(FieldNamespace))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldNamespace, v))
}

// APIVersionEQ applies the EQ predicate on the "api_version" field.
func APIVersionEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldAPIVersion, v))
}

// APIVersionNEQ applies the NEQ predicate on the "api_version" field.
func APIVersionNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldAPIVersion, v))
}

// APIVersionIn applies the In predicate on the "api_version" field.
func APIVersionIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldAPIVersion, vs...))
}

// APIVersionNotIn applies the NotIn predicate on the "api_version" field.
func APIVersionNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldAPIVersion, vs...))
}

// APIVersionGT applies the GT predicate on the "api_version" field.
func APIVersionGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldAPIVersion, v))
}

// APIVersionGTE applies the GTE predicate on the "api_version" field.
func APIVersionGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldAPIVersion, v))
}

// APIVersionLT applies the LT predicate on the "api_version" field.
func APIVersionLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldAPIVersion, v))
}

// APIVersionLTE applies the LTE predicate on the "api_version" field.
func APIVersionLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldAPIVersion, v))
}

// APIVersionContains applies the Contains predicate on the "api_version" field.
func APIVersionContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldAPIVersion, v))
}

// APIVersionHasPrefix applies the HasPrefix predicate on the "api_version" field.
func APIVersionHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldAPIVersion, v))
}

// APIVersionHasSuffix applies the HasSuffix predicate on the "api_version" field.
func APIVersionHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldAPIVersion, v))
}

// APIVersionEqualFold applies the EqualFold predicate on the "api_version" field.
func APIVersionEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldAPIVersion, v))
}

// APIVersionContainsFold applies the ContainsFold predicate on the "api_version" field.
func APIVersionContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldAPIVersion, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldKind, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldUpdatedAt, v))
}

// ResourceVersionEQ applies the EQ predicate on the "resource_version" field.
func ResourceVersionEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldResourceVersion, v))
}

// ResourceVersionNEQ applies the NEQ predicate on the "resource_version" field.
func ResourceVersionNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldResourceVersion, v))
}

// ResourceVersionIn applies the In predicate on the "resource_version" field.
func ResourceVersionIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldResourceVersion, vs...))
}

// ResourceVersionNotIn applies the NotIn predicate on the "resource_version" field.
func ResourceVersionNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldResourceVersion, vs...))
}

// ResourceVersionGT applies the GT predicate on the "resource_version" field.
func ResourceVersionGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldResourceVersion, v))
}

// ResourceVersionGTE applies the GTE predicate on the "resource_version" field.
func ResourceVersionGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldResourceVersion, v))
}

// ResourceVersionLT applies the LT predicate on the "resource_version" field.
func ResourceVersionLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldResourceVersion, v))
}

// ResourceVersionLTE applies the LTE predicate on the "resource_version" field.
func ResourceVersionLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldResourceVersion, v))
}

// ResourceVersionContains applies the Contains predicate on the "resource_version" field.
func ResourceVersionContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldResourceVersion, v))
}

// ResourceVersionHasPrefix applies the HasPrefix predicate on the "resource_version" field.
func ResourceVersionHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldResourceVersion, v))
}

// ResourceVersionHasSuffix applies the HasSuffix predicate on the "resource_version" field.
func ResourceVersionHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldResourceVersion, v))
}

// ResourceVersionEqualFold applies the EqualFold predicate on the "resource_version" field.
func ResourceVersionEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldResourceVersion, v))
}

// ResourceVersionContainsFold applies the ContainsFold predicate on the "resource_version" field.
func ResourceVersionContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldResourceVersion, v))
}

// SpecDataIsNil applies the IsNil predicate on the "spec_data" field.
func SpecDataIsNil() predicate.Named {
	return predicate.Named(sql.FieldIsNull(FieldSpecData))
}

// SpecDataNotNil applies the NotNil predicate on the "spec_data" field.
func SpecDataNotNil() predicate.Named {
	return predicate.Named(sql.FieldNotNull(FieldSpecData))
}

// SpecNameEQ applies the EQ predicate on the "spec_name" field.
func SpecNameEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecName, v))
}

// SpecNameNEQ applies the NEQ predicate on the "spec_name" field.
func SpecNameNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldSpecName, v))
}

// SpecNameIn applies the In predicate on the "spec_name" field.
func SpecNameIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldSpecName, vs...))
}

// SpecNameNotIn applies the NotIn predicate on the "spec_name" field.
func SpecNameNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldSpecName, vs...))
}

// SpecNameGT applies the GT predicate on the "spec_name" field.
func SpecNameGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldSpecName, v))
}

// SpecNameGTE applies the GTE predicate on the "spec_name" field.
func SpecNameGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldSpecName, v))
}

// SpecNameLT applies the LT predicate on the "spec_name" field.
func SpecNameLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldSpecName, v))
}

// SpecNameLTE applies the LTE predicate on the "spec_name" field.
func SpecNameLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldSpecName, v))
}

// SpecNameContains applies the Contains predicate on the "spec_name" field.
func SpecNameContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldSpecName, v))
}

// SpecNameHasPrefix applies the HasPrefix predicate on the "spec_name" field.
func SpecNameHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldSpecName, v))
}

// SpecNameHasSuffix applies the HasSuffix predicate on the "spec_name" field.
func SpecNameHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldSpecName, v))
}

// SpecNameIsNil applies the IsNil predicate on the "spec_name" field.
func SpecNameIsNil() predicate.Named {
	return predicate.Named(sql.FieldIsNull(FieldSpecName))
}

// SpecNameNotNil applies the NotNil predicate on the "spec_name" field.
func SpecNameNotNil() predicate.Named {
	return predicate.Named(sql.FieldNotNull(FieldSpecName))
}

// SpecNameEqualFold applies the EqualFold predicate on the "spec_name" field.
func SpecNameEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldSpecName, v))
}

// SpecNameContainsFold applies the ContainsFold predicate on the "spec_name" field.
func SpecNameContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldSpecName, v))
}

// SpecAltNameEQ applies the EQ predicate on the "spec_alt_name" field.
func SpecAltNameEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecAltName, v))
}

// SpecAltNameNEQ applies the NEQ predicate on the "spec_alt_name" field.
func SpecAltNameNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldSpecAltName, v))
}

// SpecAltNameIn applies the In predicate on the "spec_alt_name" field.
func SpecAltNameIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldSpecAltName, vs...))
}

// SpecAltNameNotIn applies the NotIn predicate on the "spec_alt_name" field.
func SpecAltNameNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldSpecAltName, vs...))
}

// SpecAltNameGT applies the GT predicate on the "spec_alt_name" field.
func SpecAltNameGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldSpecAltName, v))
}

// SpecAltNameGTE applies the GTE predicate on the "spec_alt_name" field.
func SpecAltNameGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldSpecAltName, v))
}

// SpecAltNameLT applies the LT predicate on the "spec_alt_name" field.
func SpecAltNameLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldSpecAltName, v))
}

// SpecAltNameLTE applies the LTE predicate on the "spec_alt_name" field.
func SpecAltNameLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldSpecAltName, v))
}

// SpecAltNameContains applies the Contains predicate on the "spec_alt_name" field.
func SpecAltNameContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldSpecAltName, v))
}

// SpecAltNameHasPrefix applies the HasPrefix predicate on the "spec_alt_name" field.
func SpecAltNameHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldSpecAltName, v))
}

// SpecAltNameHasSuffix applies the HasSuffix predicate on the "spec_alt_name" field.
func SpecAltNameHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldSpecAltName, v))
}

// SpecAltNameEqualFold applies the EqualFold predicate on the "spec_alt_name" field.
func SpecAltNameEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldSpecAltName, v))
}

// SpecAltNameContainsFold applies the ContainsFold predicate on the "spec_alt_name" field.
func SpecAltNameContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldSpecAltName, v))
}

// SpecNumberEQ applies the EQ predicate on the "spec_number" field.
func SpecNumberEQ(v int) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecNumber, v))
}

// SpecNumberNEQ applies the NEQ predicate on the "spec_number" field.
func SpecNumberNEQ(v int) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldSpecNumber, v))
}

// SpecNumberIn applies the In predicate on the "spec_number" field.
func SpecNumberIn(vs ...int) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldSpecNumber, vs...))
}

// SpecNumberNotIn applies the NotIn predicate on the "spec_number" field.
func SpecNumberNotIn(vs ...int) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldSpecNumber, vs...))
}

// SpecNumberGT applies the GT predicate on the "spec_number" field.
func SpecNumberGT(v int) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldSpecNumber, v))
}

// SpecNumberGTE applies the GTE predicate on the "spec_number" field.
func SpecNumberGTE(v int) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldSpecNumber, v))
}

// SpecNumberLT applies the LT predicate on the "spec_number" field.
func SpecNumberLT(v int) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldSpecNumber, v))
}

// SpecNumberLTE applies the LTE predicate on the "spec_number" field.
func SpecNumberLTE(v int) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldSpecNumber, v))
}

// SpecNumberIsNil applies the IsNil predicate on the "spec_number" field.
func SpecNumberIsNil() predicate.Named {
	return predicate.Named(sql.FieldIsNull(FieldSpecNumber))
}

// SpecNumberNotNil applies the NotNil predicate on the "spec_number" field.
func SpecNumberNotNil() predicate.Named {
	return predicate.Named(sql.FieldNotNull(FieldSpecNumber))
}

// SpecSomethingOrNothingEQ applies the EQ predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldEQ(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingNEQ applies the NEQ predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingNEQ(v string) predicate.Named {
	return predicate.Named(sql.FieldNEQ(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingIn applies the In predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldIn(FieldSpecSomethingOrNothing, vs...))
}

// SpecSomethingOrNothingNotIn applies the NotIn predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingNotIn(vs ...string) predicate.Named {
	return predicate.Named(sql.FieldNotIn(FieldSpecSomethingOrNothing, vs...))
}

// SpecSomethingOrNothingGT applies the GT predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingGT(v string) predicate.Named {
	return predicate.Named(sql.FieldGT(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingGTE applies the GTE predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingGTE(v string) predicate.Named {
	return predicate.Named(sql.FieldGTE(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingLT applies the LT predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingLT(v string) predicate.Named {
	return predicate.Named(sql.FieldLT(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingLTE applies the LTE predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingLTE(v string) predicate.Named {
	return predicate.Named(sql.FieldLTE(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingContains applies the Contains predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingContains(v string) predicate.Named {
	return predicate.Named(sql.FieldContains(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingHasPrefix applies the HasPrefix predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingHasPrefix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasPrefix(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingHasSuffix applies the HasSuffix predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingHasSuffix(v string) predicate.Named {
	return predicate.Named(sql.FieldHasSuffix(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingIsNil applies the IsNil predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingIsNil() predicate.Named {
	return predicate.Named(sql.FieldIsNull(FieldSpecSomethingOrNothing))
}

// SpecSomethingOrNothingNotNil applies the NotNil predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingNotNil() predicate.Named {
	return predicate.Named(sql.FieldNotNull(FieldSpecSomethingOrNothing))
}

// SpecSomethingOrNothingEqualFold applies the EqualFold predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingEqualFold(v string) predicate.Named {
	return predicate.Named(sql.FieldEqualFold(FieldSpecSomethingOrNothing, v))
}

// SpecSomethingOrNothingContainsFold applies the ContainsFold predicate on the "spec_something_or_nothing" field.
func SpecSomethingOrNothingContainsFold(v string) predicate.Named {
	return predicate.Named(sql.FieldContainsFold(FieldSpecSomethingOrNothing, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Named) predicate.Named {
	return predicate.Named(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Named) predicate.Named {
	return predicate.Named(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Named) predicate.Named {
	return predicate.Named(sql.NotPredicates(p))
}
