// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetHealth(ctx) - Get service health status
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil, client.DefaultLogger())
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient, client.DefaultLogger)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"

	"github.com/openchami/fabrica/pkg/fabrica"
	"github.com/rs/zerolog"
	"github.com/spf13/cobra"

	"github.com/openchami/inventory-service/apis/inventory-service.openchami.org/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL     *url.URL
	httpClient  *http.Client
	logger      zerolog.Logger
	version     string // Optional API version for Accept/Content-Type headers
	bearerToken string // Optional JWT bearer token for Authorization header
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse represents a generic service health payload.
// Services may return additional fields beyond the common ones.
type HealthResponse map[string]interface{}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client, logger zerolog.Logger) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
		logger:     logger,
	}, nil
}

// NewClientWithBearerToken creates a new API client configured with a JWT bearer token.
func NewClientWithBearerToken(baseURL, bearerToken string, httpClient *http.Client, logger zerolog.Logger) (*Client, error) {
	c, err := NewClient(baseURL, httpClient, logger)
	if err != nil {
		return nil, err
	}
	return c.WithBearerToken(bearerToken), nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     version,
		bearerToken: c.bearerToken,
		logger:      c.logger,
	}
}

// WithBearerToken returns a new client configured to send Authorization: Bearer <token>.
func (c *Client) WithBearerToken(token string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     c.version,
		bearerToken: token,
		logger:      c.logger,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	// Debug info for request
	c.logger.Debug().Msgf("%s: %s", method, u.String())
	if len(req.Header) > 0 {
		c.logger.Debug().Msg("Request headers:")
		for k, v := range req.Header {
			c.logger.Debug().Msgf("  %s: %s", k, v)
		}
	} else {
		c.logger.Debug().Msg("No headers in request")
	}
	if req.ContentLength > 0 {
		var reqBodyCopy bytes.Buffer
		reqBodyReader := io.TeeReader(req.Body, &reqBodyCopy)
		reqBodyBytes, err := io.ReadAll(reqBodyReader)
		if err != nil {
			c.logger.Error().Err(err).Msg("failed to read body for debug message")
		}
		c.logger.Debug().Msg("Request body:")
		c.logger.Debug().Msgf("%s", string(reqBodyBytes))
		req.Body = io.NopCloser(bytes.NewReader(reqBodyBytes))
	} else {
		c.logger.Debug().Msg("No body in request")
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	// Debug info for response
	if resp != nil {
		c.logger.Debug().Msg("Response status: " + resp.Status)
		if len(resp.Header) > 0 {
			c.logger.Debug().Msg("Response headers:")
			for k, v := range resp.Header {
				c.logger.Debug().Msgf("  %s: %s", k, v)
			}
		} else {
			c.logger.Debug().Msg("No headers in response")
		}
		respBodyLen := resp.ContentLength
		if respBodyLen > 0 {
			var respBodyCopy bytes.Buffer
			respBodyReader := io.TeeReader(resp.Body, &respBodyCopy)
			respBodyBytes, err := io.ReadAll(respBodyReader)
			if err != nil {
				c.logger.Error().Err(err).Msg("failed to read body for debug message")
			}
			c.logger.Debug().Msg("Response body:")
			c.logger.Debug().Msgf("%s", string(respBodyBytes))
			resp.Body = io.NopCloser(bytes.NewReader(respBodyBytes))
		} else {
			c.logger.Debug().Msg("No body in response")
		}
	} else {
		c.logger.Debug().Msg("Response was nil")
	}

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetHealth retrieves the service health endpoint response.
func (c *Client) GetHealth(ctx context.Context) (HealthResponse, error) {
	result := HealthResponse{}
	if err := c.doRequest(ctx, "GET", "health", nil, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// GetComponents retrieves all components
func (c *Client) GetComponents(ctx context.Context) ([]v1.Component, error) {
	var response []v1.Component
	if err := c.doRequest(ctx, "GET", "/components", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetComponent retrieves a specific Component by UID
func (c *Client) GetComponent(ctx context.Context, uid string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateComponentSimple creates a new Component with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateComponent instead.
//
// Example:
//
//	spec := v1.ComponentSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateComponentSimple(ctx, "my-resource", spec)
func (c *Client) CreateComponentSimple(ctx context.Context, name string, spec v1.ComponentSpec) (*v1.Component, error) {
	req := CreateComponentRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateComponent(ctx, req)
}

// CreateComponent creates a new Component (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateComponentSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateComponentRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateComponent(ctx, req)
func (c *Client) CreateComponent(ctx context.Context, req CreateComponentRequest) (*v1.Component, error) {
	var result v1.Component
	if err := c.doRequest(ctx, "POST", "/components", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentSimple updates an existing Component's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateComponent instead.
//
// Example:
//
//	spec := v1.ComponentSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateComponentSimple(ctx, uid, spec)
func (c *Client) UpdateComponentSimple(ctx context.Context, uid string, spec v1.ComponentSpec) (*v1.Component, error) {
	req := UpdateComponentRequest{
		Spec: spec,
	}
	return c.UpdateComponent(ctx, uid, req)
}

// UpdateComponent updates an existing Component (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateComponentSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateComponentRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateComponent(ctx, uid, req)
func (c *Client) UpdateComponent(ctx context.Context, uid string, req UpdateComponentRequest) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponent patches an existing Component spec with the specified patch data and content type
func (c *Client) PatchComponent(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentStatus updates only the status of an existing Component
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateComponentStatus(ctx context.Context, uid string, status v1.ComponentStatus) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentStatus patches only the status of an existing Component
// Supports JSON Merge Patch by default. Use PatchComponentStatusWithType for other patch formats.
func (c *Client) PatchComponentStatus(ctx context.Context, uid string, patchData []byte) (*v1.Component, error) {
	return c.PatchComponentStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchComponentStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchComponentStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteComponent deletes a Component by UID
func (c *Client) DeleteComponent(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/components/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetComponentEndpoints retrieves all componentendpoints
func (c *Client) GetComponentEndpoints(ctx context.Context) ([]v1.ComponentEndpoint, error) {
	var response []v1.ComponentEndpoint
	if err := c.doRequest(ctx, "GET", "/componentendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetComponentEndpoint retrieves a specific ComponentEndpoint by UID
func (c *Client) GetComponentEndpoint(ctx context.Context, uid string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateComponentEndpointSimple creates a new ComponentEndpoint with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateComponentEndpoint instead.
//
// Example:
//
//	spec := v1.ComponentEndpointSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateComponentEndpointSimple(ctx, "my-resource", spec)
func (c *Client) CreateComponentEndpointSimple(ctx context.Context, name string, spec v1.ComponentEndpointSpec) (*v1.ComponentEndpoint, error) {
	req := CreateComponentEndpointRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateComponentEndpoint(ctx, req)
}

// CreateComponentEndpoint creates a new ComponentEndpoint (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateComponentEndpointSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateComponentEndpointRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateComponentEndpoint(ctx, req)
func (c *Client) CreateComponentEndpoint(ctx context.Context, req CreateComponentEndpointRequest) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	if err := c.doRequest(ctx, "POST", "/componentendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentEndpointSimple updates an existing ComponentEndpoint's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateComponentEndpoint instead.
//
// Example:
//
//	spec := v1.ComponentEndpointSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateComponentEndpointSimple(ctx, uid, spec)
func (c *Client) UpdateComponentEndpointSimple(ctx context.Context, uid string, spec v1.ComponentEndpointSpec) (*v1.ComponentEndpoint, error) {
	req := UpdateComponentEndpointRequest{
		Spec: spec,
	}
	return c.UpdateComponentEndpoint(ctx, uid, req)
}

// UpdateComponentEndpoint updates an existing ComponentEndpoint (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateComponentEndpointSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateComponentEndpointRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateComponentEndpoint(ctx, uid, req)
func (c *Client) UpdateComponentEndpoint(ctx context.Context, uid string, req UpdateComponentEndpointRequest) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentEndpoint patches an existing ComponentEndpoint spec with the specified patch data and content type
func (c *Client) PatchComponentEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentEndpointStatus updates only the status of an existing ComponentEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateComponentEndpointStatus(ctx context.Context, uid string, status v1.ComponentEndpointStatus) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentEndpointStatus patches only the status of an existing ComponentEndpoint
// Supports JSON Merge Patch by default. Use PatchComponentEndpointStatusWithType for other patch formats.
func (c *Client) PatchComponentEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.ComponentEndpoint, error) {
	return c.PatchComponentEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchComponentEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchComponentEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteComponentEndpoint deletes a ComponentEndpoint by UID
func (c *Client) DeleteComponentEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetEthernetInterfaces retrieves all ethernetinterfaces
func (c *Client) GetEthernetInterfaces(ctx context.Context) ([]v1.EthernetInterface, error) {
	var response []v1.EthernetInterface
	if err := c.doRequest(ctx, "GET", "/ethernetinterfaces", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetEthernetInterface retrieves a specific EthernetInterface by UID
func (c *Client) GetEthernetInterface(ctx context.Context, uid string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateEthernetInterfaceSimple creates a new EthernetInterface with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateEthernetInterface instead.
//
// Example:
//
//	spec := v1.EthernetInterfaceSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateEthernetInterfaceSimple(ctx, "my-resource", spec)
func (c *Client) CreateEthernetInterfaceSimple(ctx context.Context, name string, spec v1.EthernetInterfaceSpec) (*v1.EthernetInterface, error) {
	req := CreateEthernetInterfaceRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateEthernetInterface(ctx, req)
}

// CreateEthernetInterface creates a new EthernetInterface (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateEthernetInterfaceSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateEthernetInterfaceRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateEthernetInterface(ctx, req)
func (c *Client) CreateEthernetInterface(ctx context.Context, req CreateEthernetInterfaceRequest) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	if err := c.doRequest(ctx, "POST", "/ethernetinterfaces", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateEthernetInterfaceSimple updates an existing EthernetInterface's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateEthernetInterface instead.
//
// Example:
//
//	spec := v1.EthernetInterfaceSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateEthernetInterfaceSimple(ctx, uid, spec)
func (c *Client) UpdateEthernetInterfaceSimple(ctx context.Context, uid string, spec v1.EthernetInterfaceSpec) (*v1.EthernetInterface, error) {
	req := UpdateEthernetInterfaceRequest{
		Spec: spec,
	}
	return c.UpdateEthernetInterface(ctx, uid, req)
}

// UpdateEthernetInterface updates an existing EthernetInterface (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateEthernetInterfaceSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateEthernetInterfaceRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateEthernetInterface(ctx, uid, req)
func (c *Client) UpdateEthernetInterface(ctx context.Context, uid string, req UpdateEthernetInterfaceRequest) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchEthernetInterface patches an existing EthernetInterface spec with the specified patch data and content type
func (c *Client) PatchEthernetInterface(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateEthernetInterfaceStatus updates only the status of an existing EthernetInterface
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateEthernetInterfaceStatus(ctx context.Context, uid string, status v1.EthernetInterfaceStatus) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchEthernetInterfaceStatus patches only the status of an existing EthernetInterface
// Supports JSON Merge Patch by default. Use PatchEthernetInterfaceStatusWithType for other patch formats.
func (c *Client) PatchEthernetInterfaceStatus(ctx context.Context, uid string, patchData []byte) (*v1.EthernetInterface, error) {
	return c.PatchEthernetInterfaceStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchEthernetInterfaceStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchEthernetInterfaceStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteEthernetInterface deletes a EthernetInterface by UID
func (c *Client) DeleteEthernetInterface(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetGroups retrieves all groups
func (c *Client) GetGroups(ctx context.Context) ([]v1.Group, error) {
	var response []v1.Group
	if err := c.doRequest(ctx, "GET", "/groups", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetGroup retrieves a specific Group by UID
func (c *Client) GetGroup(ctx context.Context, uid string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateGroupSimple creates a new Group with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateGroup instead.
//
// Example:
//
//	spec := v1.GroupSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateGroupSimple(ctx, "my-resource", spec)
func (c *Client) CreateGroupSimple(ctx context.Context, name string, spec v1.GroupSpec) (*v1.Group, error) {
	req := CreateGroupRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateGroup(ctx, req)
}

// CreateGroup creates a new Group (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateGroupSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateGroupRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateGroup(ctx, req)
func (c *Client) CreateGroup(ctx context.Context, req CreateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	if err := c.doRequest(ctx, "POST", "/groups", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupSimple updates an existing Group's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateGroup instead.
//
// Example:
//
//	spec := v1.GroupSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateGroupSimple(ctx, uid, spec)
func (c *Client) UpdateGroupSimple(ctx context.Context, uid string, spec v1.GroupSpec) (*v1.Group, error) {
	req := UpdateGroupRequest{
		Spec: spec,
	}
	return c.UpdateGroup(ctx, uid, req)
}

// UpdateGroup updates an existing Group (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateGroupSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateGroupRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateGroup(ctx, uid, req)
func (c *Client) UpdateGroup(ctx context.Context, uid string, req UpdateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroup patches an existing Group spec with the specified patch data and content type
func (c *Client) PatchGroup(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupStatus updates only the status of an existing Group
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateGroupStatus(ctx context.Context, uid string, status v1.GroupStatus) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroupStatus patches only the status of an existing Group
// Supports JSON Merge Patch by default. Use PatchGroupStatusWithType for other patch formats.
func (c *Client) PatchGroupStatus(ctx context.Context, uid string, patchData []byte) (*v1.Group, error) {
	return c.PatchGroupStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchGroupStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchGroupStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteGroup deletes a Group by UID
func (c *Client) DeleteGroup(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/groups/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetHardwares retrieves all hardwares
func (c *Client) GetHardwares(ctx context.Context) ([]v1.Hardware, error) {
	var response []v1.Hardware
	if err := c.doRequest(ctx, "GET", "/hardwares", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetHardware retrieves a specific Hardware by UID
func (c *Client) GetHardware(ctx context.Context, uid string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateHardwareSimple creates a new Hardware with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateHardware instead.
//
// Example:
//
//	spec := v1.HardwareSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateHardwareSimple(ctx, "my-resource", spec)
func (c *Client) CreateHardwareSimple(ctx context.Context, name string, spec v1.HardwareSpec) (*v1.Hardware, error) {
	req := CreateHardwareRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateHardware(ctx, req)
}

// CreateHardware creates a new Hardware (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateHardwareSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateHardwareRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateHardware(ctx, req)
func (c *Client) CreateHardware(ctx context.Context, req CreateHardwareRequest) (*v1.Hardware, error) {
	var result v1.Hardware
	if err := c.doRequest(ctx, "POST", "/hardwares", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateHardwareSimple updates an existing Hardware's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateHardware instead.
//
// Example:
//
//	spec := v1.HardwareSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateHardwareSimple(ctx, uid, spec)
func (c *Client) UpdateHardwareSimple(ctx context.Context, uid string, spec v1.HardwareSpec) (*v1.Hardware, error) {
	req := UpdateHardwareRequest{
		Spec: spec,
	}
	return c.UpdateHardware(ctx, uid, req)
}

// UpdateHardware updates an existing Hardware (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateHardwareSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateHardwareRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateHardware(ctx, uid, req)
func (c *Client) UpdateHardware(ctx context.Context, uid string, req UpdateHardwareRequest) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchHardware patches an existing Hardware spec with the specified patch data and content type
func (c *Client) PatchHardware(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateHardwareStatus updates only the status of an existing Hardware
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateHardwareStatus(ctx context.Context, uid string, status v1.HardwareStatus) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchHardwareStatus patches only the status of an existing Hardware
// Supports JSON Merge Patch by default. Use PatchHardwareStatusWithType for other patch formats.
func (c *Client) PatchHardwareStatus(ctx context.Context, uid string, patchData []byte) (*v1.Hardware, error) {
	return c.PatchHardwareStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchHardwareStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchHardwareStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteHardware deletes a Hardware by UID
func (c *Client) DeleteHardware(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetRedfishEndpoints retrieves all redfishendpoints
func (c *Client) GetRedfishEndpoints(ctx context.Context) ([]v1.RedfishEndpoint, error) {
	var response []v1.RedfishEndpoint
	if err := c.doRequest(ctx, "GET", "/redfishendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetRedfishEndpoint retrieves a specific RedfishEndpoint by UID
func (c *Client) GetRedfishEndpoint(ctx context.Context, uid string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateRedfishEndpointSimple creates a new RedfishEndpoint with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateRedfishEndpoint instead.
//
// Example:
//
//	spec := v1.RedfishEndpointSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateRedfishEndpointSimple(ctx, "my-resource", spec)
func (c *Client) CreateRedfishEndpointSimple(ctx context.Context, name string, spec v1.RedfishEndpointSpec) (*v1.RedfishEndpoint, error) {
	req := CreateRedfishEndpointRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateRedfishEndpoint(ctx, req)
}

// CreateRedfishEndpoint creates a new RedfishEndpoint (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateRedfishEndpointSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateRedfishEndpointRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateRedfishEndpoint(ctx, req)
func (c *Client) CreateRedfishEndpoint(ctx context.Context, req CreateRedfishEndpointRequest) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	if err := c.doRequest(ctx, "POST", "/redfishendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateRedfishEndpointSimple updates an existing RedfishEndpoint's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateRedfishEndpoint instead.
//
// Example:
//
//	spec := v1.RedfishEndpointSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateRedfishEndpointSimple(ctx, uid, spec)
func (c *Client) UpdateRedfishEndpointSimple(ctx context.Context, uid string, spec v1.RedfishEndpointSpec) (*v1.RedfishEndpoint, error) {
	req := UpdateRedfishEndpointRequest{
		Spec: spec,
	}
	return c.UpdateRedfishEndpoint(ctx, uid, req)
}

// UpdateRedfishEndpoint updates an existing RedfishEndpoint (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateRedfishEndpointSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateRedfishEndpointRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateRedfishEndpoint(ctx, uid, req)
func (c *Client) UpdateRedfishEndpoint(ctx context.Context, uid string, req UpdateRedfishEndpointRequest) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchRedfishEndpoint patches an existing RedfishEndpoint spec with the specified patch data and content type
func (c *Client) PatchRedfishEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateRedfishEndpointStatus updates only the status of an existing RedfishEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateRedfishEndpointStatus(ctx context.Context, uid string, status v1.RedfishEndpointStatus) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchRedfishEndpointStatus patches only the status of an existing RedfishEndpoint
// Supports JSON Merge Patch by default. Use PatchRedfishEndpointStatusWithType for other patch formats.
func (c *Client) PatchRedfishEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.RedfishEndpoint, error) {
	return c.PatchRedfishEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchRedfishEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchRedfishEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteRedfishEndpoint deletes a RedfishEndpoint by UID
func (c *Client) DeleteRedfishEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetServiceEndpoints retrieves all serviceendpoints
func (c *Client) GetServiceEndpoints(ctx context.Context) ([]v1.ServiceEndpoint, error) {
	var response []v1.ServiceEndpoint
	if err := c.doRequest(ctx, "GET", "/serviceendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetServiceEndpoint retrieves a specific ServiceEndpoint by UID
func (c *Client) GetServiceEndpoint(ctx context.Context, uid string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateServiceEndpointSimple creates a new ServiceEndpoint with minimal boilerplate (Simple API)
//
// This is the recommended method for most use cases. It only requires a name and spec,
// and the client automatically handles the resource envelope (APIVersion, Kind, Metadata).
//
// Use this when:
//   - You only need to set the resource name and spec
//   - You don't need custom labels or annotations
//   - You want the simplest possible API
//
// For advanced use cases (labels, annotations, custom metadata), use CreateServiceEndpoint instead.
//
// Example:
//
//	spec := v1.ServiceEndpointSpec{
//	    // ... your spec fields
//	}
//	resource, err := client.CreateServiceEndpointSimple(ctx, "my-resource", spec)
func (c *Client) CreateServiceEndpointSimple(ctx context.Context, name string, spec v1.ServiceEndpointSpec) (*v1.ServiceEndpoint, error) {
	req := CreateServiceEndpointRequest{
		Metadata: fabrica.Metadata{
			Name: name,
		},
		Spec: spec,
	}
	return c.CreateServiceEndpoint(ctx, req)
}

// CreateServiceEndpoint creates a new ServiceEndpoint (Advanced API)
//
// This method provides full control over the resource envelope, including labels and annotations.
// Most users should use CreateServiceEndpointSimple instead.
//
// Use this when:
//   - You need to set labels or annotations
//   - You need full control over metadata fields
//   - You're migrating from code that already constructs requests
//
// Example:
//
//	req := CreateServiceEndpointRequest{
//	    Metadata: fabrica.Metadata{Name: "my-resource"},
//	    Spec: spec,
//	    Labels: map[string]string{"env": "prod"},
//	}
//	resource, err := client.CreateServiceEndpoint(ctx, req)
func (c *Client) CreateServiceEndpoint(ctx context.Context, req CreateServiceEndpointRequest) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	if err := c.doRequest(ctx, "POST", "/serviceendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateServiceEndpointSimple updates an existing ServiceEndpoint's spec (Simple API)
//
// This is the recommended method for most update operations. It only requires the UID
// and the new spec, preserving all existing metadata.
//
// Use this when:
//   - You only need to update the spec
//   - You want to preserve existing labels and annotations
//   - You want the simplest possible API
//
// For advanced use cases (updating labels/annotations), use UpdateServiceEndpoint instead.
//
// Example:
//
//	spec := v1.ServiceEndpointSpec{
//	    // ... updated spec fields
//	}
//	resource, err := client.UpdateServiceEndpointSimple(ctx, uid, spec)
func (c *Client) UpdateServiceEndpointSimple(ctx context.Context, uid string, spec v1.ServiceEndpointSpec) (*v1.ServiceEndpoint, error) {
	req := UpdateServiceEndpointRequest{
		Spec: spec,
	}
	return c.UpdateServiceEndpoint(ctx, uid, req)
}

// UpdateServiceEndpoint updates an existing ServiceEndpoint (Advanced API)
//
// This method provides full control over what gets updated, including metadata fields.
// Most users should use UpdateServiceEndpointSimple instead.
//
// Use this when:
//   - You need to update labels or annotations
//   - You need to update the resource name
//   - You need full control over what fields get updated
//
// Example:
//
//	req := UpdateServiceEndpointRequest{
//	    Spec: spec,
//	    Labels: map[string]string{"env": "staging"},
//	}
//	resource, err := client.UpdateServiceEndpoint(ctx, uid, req)
func (c *Client) UpdateServiceEndpoint(ctx context.Context, uid string, req UpdateServiceEndpointRequest) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchServiceEndpoint patches an existing ServiceEndpoint spec with the specified patch data and content type
func (c *Client) PatchServiceEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateServiceEndpointStatus updates only the status of an existing ServiceEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateServiceEndpointStatus(ctx context.Context, uid string, status v1.ServiceEndpointStatus) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchServiceEndpointStatus patches only the status of an existing ServiceEndpoint
// Supports JSON Merge Patch by default. Use PatchServiceEndpointStatusWithType for other patch formats.
func (c *Client) PatchServiceEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.ServiceEndpoint, error) {
	return c.PatchServiceEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchServiceEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchServiceEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteServiceEndpoint deletes a ServiceEndpoint by UID
func (c *Client) DeleteServiceEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// LogLevel represents a valid log level
type LogLevel string

const (
	LogLevelInfo    LogLevel = "info"
	LogLevelWarning LogLevel = "warning"
	LogLevelDebug   LogLevel = "debug"
)

var (
	LogLevelHelp = map[string]string{
		string(LogLevelInfo):    "Info log level",
		string(LogLevelWarning): "Warning log level",
		string(LogLevelDebug):   "Debug log level",
	}
)

func (ll LogLevel) String() string {
	return string(ll)
}

func (ll *LogLevel) Set(v string) error {
	switch LogLevel(v) {
	case LogLevelInfo,
		LogLevelWarning,
		LogLevelDebug:
		*ll = LogLevel(v)
		return nil
	default:
		return fmt.Errorf("must be one of %v", []LogLevel{
			LogLevelInfo,
			LogLevelWarning,
			LogLevelDebug,
		})
	}
}

func (ll LogLevel) Type() string {
	return "LogLevel"
}

// CompletionLogLevel is the cobra completion function for the --log-level
// flag.
func CompletionLogLevel(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
	var helpSlice []string
	for k, v := range LogLevelHelp {
		helpSlice = append(helpSlice, fmt.Sprintf("%s\t%s", k, v))
	}
	return helpSlice, cobra.ShellCompDirectiveDefault
}

func DefaultLogger() zerolog.Logger {
	cw := zerolog.ConsoleWriter{
		Out:          os.Stderr,
		PartsExclude: []string{zerolog.TimestampFieldName},
	}
	return zerolog.New(cw).Level(zerolog.WarnLevel)
}

func NewLogger(level LogLevel) (zerolog.Logger, error) {
	cw := zerolog.ConsoleWriter{
		Out:          os.Stderr,
		PartsExclude: []string{zerolog.TimestampFieldName},
	}
	l := zerolog.New(cw)
	var ll zerolog.Level
	switch level {
	case LogLevelWarning:
		ll = zerolog.WarnLevel
	case LogLevelInfo:
		ll = zerolog.InfoLevel
	case LogLevelDebug:
		ll = zerolog.DebugLevel
	default:
		return DefaultLogger(), fmt.Errorf("invalid log level: %s", level)
	}
	return l.Level(ll), nil
}
