// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains client-side request/response models.
// Generated from: pkg/codegen/templates/client-models.go.tmpl
//
// To modify client models:
//   1. Edit the template file: pkg/codegen/templates/client-models.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// DEPRECATED: This template is a legacy stub. The actual client models are
// generated in models.go.tmpl and used by both server and client.
//
// Generated request types:
//   - CreateResourceRequest: Create operation with metadata
//   - UpdateResourceRequest: Update operation with partial fields
//   - DeleteResponse: Confirmation of deletion
//
// Note: This file contains TODO comments indicating that resource-specific
// fields should be added. Consider migrating to the unified models.go.tmpl
// approach or implementing spec field embedding.
//
// To implement full spec support:
//   1. Import resource packages
//   2. Embed ResourceSpec in request structs
//   3. Use json:",inline" tag for proper serialization
//
// To add validation:
//   1. Add validate tags (e.g., validate:"required,min=3")
//   2. Use go-playground/validator in client before sending
//

// Package client provides generated client-side request and response models.
package client

import (
	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/openchami/inventory-service/apis/inventory-service.openchami.org/v1"
)

// CreateComponentRequest represents a request to create a Component (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateComponentSimple in the client.
type CreateComponentRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.ComponentSpec  `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateComponentRequest represents a request to update a Component (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateComponentSimple in the client.
type UpdateComponentRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.ComponentSpec  `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateComponentEndpointRequest represents a request to create a ComponentEndpoint (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateComponentEndpointSimple in the client.
type CreateComponentEndpointRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.ComponentEndpointSpec `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateComponentEndpointRequest represents a request to update a ComponentEndpoint (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateComponentEndpointSimple in the client.
type UpdateComponentEndpointRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.ComponentEndpointSpec `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateEthernetInterfaceRequest represents a request to create a EthernetInterface (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateEthernetInterfaceSimple in the client.
type CreateEthernetInterfaceRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.EthernetInterfaceSpec `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateEthernetInterfaceRequest represents a request to update a EthernetInterface (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateEthernetInterfaceSimple in the client.
type UpdateEthernetInterfaceRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.EthernetInterfaceSpec `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string        `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateGroupRequest represents a request to create a Group (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateGroupSimple in the client.
type CreateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.GroupSpec      `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateGroupRequest represents a request to update a Group (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateGroupSimple in the client.
type UpdateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.GroupSpec      `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateHardwareRequest represents a request to create a Hardware (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateHardwareSimple in the client.
type CreateHardwareRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.HardwareSpec   `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateHardwareRequest represents a request to update a Hardware (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateHardwareSimple in the client.
type UpdateHardwareRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.HardwareSpec   `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateRedfishEndpointRequest represents a request to create a RedfishEndpoint (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateRedfishEndpointSimple in the client.
type CreateRedfishEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.RedfishEndpointSpec `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateRedfishEndpointRequest represents a request to update a RedfishEndpoint (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateRedfishEndpointSimple in the client.
type UpdateRedfishEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.RedfishEndpointSpec `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// CreateServiceEndpointRequest represents a request to create a ServiceEndpoint (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateServiceEndpointSimple in the client.
type CreateServiceEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.ServiceEndpointSpec `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateServiceEndpointRequest represents a request to update a ServiceEndpoint (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateServiceEndpointSimple in the client.
type UpdateServiceEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.ServiceEndpointSpec `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}
