// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-08-28T18:16:46Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/user-service-pr-sqlite/apis/storage-annotations.openchami.org/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.User{}); err != nil {
		return fmt.Errorf("failed to register User: %w", err)
	}

	return nil
}
