// Code generated by Fabrica v0.4.10-7-g53b0071 (commit: 53b0071). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package storage

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
