// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openchami/user-service-postgres/internal/storage/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *UserCreate) SetUID(v string) *UserCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *UserCreate) SetNamespace(v string) *UserCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_c *UserCreate) SetNillableNamespace(v *string) *UserCreate {
	if v != nil {
		_c.SetNamespace(*v)
	}
	return _c
}

// SetAPIVersion sets the "api_version" field.
func (_c *UserCreate) SetAPIVersion(v string) *UserCreate {
	_c.mutation.SetAPIVersion(v)
	return _c
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_c *UserCreate) SetNillableAPIVersion(v *string) *UserCreate {
	if v != nil {
		_c.SetAPIVersion(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *UserCreate) SetKind(v string) *UserCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *UserCreate) SetNillableKind(v *string) *UserCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetResourceVersion sets the "resource_version" field.
func (_c *UserCreate) SetResourceVersion(v string) *UserCreate {
	_c.mutation.SetResourceVersion(v)
	return _c
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_c *UserCreate) SetNillableResourceVersion(v *string) *UserCreate {
	if v != nil {
		_c.SetResourceVersion(*v)
	}
	return _c
}

// SetSpecData sets the "spec_data" field.
func (_c *UserCreate) SetSpecData(v json.RawMessage) *UserCreate {
	_c.mutation.SetSpecData(v)
	return _c
}

// SetSpecUsername sets the "spec_username" field.
func (_c *UserCreate) SetSpecUsername(v string) *UserCreate {
	_c.mutation.SetSpecUsername(v)
	return _c
}

// SetNillableSpecUsername sets the "spec_username" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpecUsername(v *string) *UserCreate {
	if v != nil {
		_c.SetSpecUsername(*v)
	}
	return _c
}

// SetSpecEmail sets the "spec_email" field.
func (_c *UserCreate) SetSpecEmail(v string) *UserCreate {
	_c.mutation.SetSpecEmail(v)
	return _c
}

// SetNillableSpecEmail sets the "spec_email" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpecEmail(v *string) *UserCreate {
	if v != nil {
		_c.SetSpecEmail(*v)
	}
	return _c
}

// SetSpecPassword sets the "spec_password" field.
func (_c *UserCreate) SetSpecPassword(v string) *UserCreate {
	_c.mutation.SetSpecPassword(v)
	return _c
}

// SetNillableSpecPassword sets the "spec_password" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpecPassword(v *string) *UserCreate {
	if v != nil {
		_c.SetSpecPassword(*v)
	}
	return _c
}

// SetSpecRole sets the "spec_role" field.
func (_c *UserCreate) SetSpecRole(v string) *UserCreate {
	_c.mutation.SetSpecRole(v)
	return _c
}

// SetNillableSpecRole sets the "spec_role" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpecRole(v *string) *UserCreate {
	if v != nil {
		_c.SetSpecRole(*v)
	}
	return _c
}

// SetSpecActive sets the "spec_active" field.
func (_c *UserCreate) SetSpecActive(v bool) *UserCreate {
	_c.mutation.SetSpecActive(v)
	return _c
}

// SetNillableSpecActive sets the "spec_active" field if the given value is not nil.
func (_c *UserCreate) SetNillableSpecActive(v *bool) *UserCreate {
	if v != nil {
		_c.SetSpecActive(*v)
	}
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() error {
	if _, ok := _c.mutation.APIVersion(); !ok {
		v := user.DefaultAPIVersion
		_c.mutation.SetAPIVersion(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := user.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if user.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if user.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		v := user.DefaultResourceVersion
		_c.mutation.SetResourceVersion(v)
	}
	if _, ok := _c.mutation.SpecRole(); !ok {
		v := user.DefaultSpecRole
		_c.mutation.SetSpecRole(v)
	}
	if _, ok := _c.mutation.SpecActive(); !ok {
		v := user.DefaultSpecActive
		_c.mutation.SetSpecActive(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "User.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := user.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "User.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIVersion(); !ok {
		return &ValidationError{Name: "api_version", err: errors.New(`ent: missing required field "User.api_version"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "User.kind"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		return &ValidationError{Name: "resource_version", err: errors.New(`ent: missing required field "User.resource_version"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(user.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(user.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.APIVersion(); ok {
		_spec.SetField(user.FieldAPIVersion, field.TypeString, value)
		_node.APIVersion = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(user.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ResourceVersion(); ok {
		_spec.SetField(user.FieldResourceVersion, field.TypeString, value)
		_node.ResourceVersion = value
	}
	if value, ok := _c.mutation.SpecData(); ok {
		_spec.SetField(user.FieldSpecData, field.TypeJSON, value)
		_node.SpecData = value
	}
	if value, ok := _c.mutation.SpecUsername(); ok {
		_spec.SetField(user.FieldSpecUsername, field.TypeString, value)
		_node.SpecUsername = value
	}
	if value, ok := _c.mutation.SpecEmail(); ok {
		_spec.SetField(user.FieldSpecEmail, field.TypeString, value)
		_node.SpecEmail = value
	}
	if value, ok := _c.mutation.SpecPassword(); ok {
		_spec.SetField(user.FieldSpecPassword, field.TypeString, value)
		_node.SpecPassword = value
	}
	if value, ok := _c.mutation.SpecRole(); ok {
		_spec.SetField(user.FieldSpecRole, field.TypeString, value)
		_node.SpecRole = value
	}
	if value, ok := _c.mutation.SpecActive(); ok {
		_spec.SetField(user.FieldSpecActive, field.TypeBool, value)
		_node.SpecActive = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
