// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-08-25T20:28:15Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Node resources.
//
// To modify this code:
//   1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /nodes (list all nodes)
//   - GET /nodes/{uid} (get specific Node)
//   - POST /nodes (create new Node)
//   - PUT /nodes/{uid} (update Node spec)
//   - PATCH /nodes/{uid} (patch Node spec)
//   - DELETE /nodes/{uid} (delete Node)
//   - PUT /nodes/{uid}/status (update Node status)
//   - PATCH /nodes/{uid}/status (patch Node status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadNode*/SaveNode*/DeleteNode*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//   1. Add new version: fabrica add version <group> <version>
//   2. Implement converter: apis/<group>/<version>/converter.go
//   3. Add version-aware storage: storage.LoadNodeWithVersion()
//   4. Register versions in cmd/server/main.go
//
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/openchami/node-service-postgres/apis/node-service.openchami.org/v1"

	"github.com/openchami/node-service-postgres/internal/storage"
)

// GetNodes returns all Node resources
func GetNodes(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	nodes, err := storage.LoadAllNodes(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load nodes: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, nodes)
}

// GetNode returns a specific Node resource by UID
func GetNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadNode() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	node, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, node)
}

// CreateNode creates a new Node resource
func CreateNode(w http.ResponseWriter, r *http.Request) {
	var req CreateNodeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Node")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	node := &v1.Node{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "Node",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	node.Metadata = req.Metadata
	node.Metadata.UID = uid
	now := time.Now()
	node.Metadata.CreatedAt = now
	node.Metadata.UpdatedAt = now

	// Set labels and annotations
	if node.Metadata.Labels == nil {
		node.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		node.Metadata.Labels[k] = v
	}
	if node.Metadata.Annotations == nil {
		node.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		node.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), node); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveNode(r.Context(), node); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Node: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "Node", node.Metadata.UID, node.Metadata.Name, node); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for Node %s: %v\n", node.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, node)
}

// UpdateNode updates the spec of an existing Node resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //nodes/{uid}/status to update status.
func UpdateNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	node, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	var req UpdateNodeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		node.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	node.Spec = req.AsSpec()

	// Update labels and annotations
	if node.Metadata.Labels == nil {
		node.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		node.Metadata.Labels[k] = v
	}
	if node.Metadata.Annotations == nil {
		node.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		node.Metadata.Annotations[k] = v
	}

	// Update timestamp
	node.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), node); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveNode(r.Context(), node); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Node: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": node.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "Node", node.Metadata.UID, node.Metadata.Name, node, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for Node %s: %v\n", node.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, node)
}

// PatchNode patches an existing Node resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	node, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(node.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &node.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	node.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), node); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveNode(r.Context(), node); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Node: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": node.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "Node", node.Metadata.UID, node.Metadata.Name, node, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for Node %s: %v\n", node.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, node)
}

// UpdateNodeStatus updates only the status of a Node resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateNodeStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	var statusUpdate v1.NodeStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveNode(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Node status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "Node", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for Node %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchNodeStatus patches only the status of a Node resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchNodeStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveNode(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Node status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "Node", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for Node %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteNode deletes a Node resource
func DeleteNode(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Node UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	node, err := storage.LoadNode(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Node not found: %w", err))
		return
	}

	if err := storage.DeleteNode(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Node: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "Node", node.Metadata.UID, node.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for Node %s: %v\n", node.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Node deleted successfully",
		UID:     uid,
	})
}
