// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/named-resource-service/apis/named-resource-service.openchami.org/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.Named{}); err != nil {
		return fmt.Errorf("failed to register Named: %w", err)
	}

	return nil
}
