// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package storage

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openchami/fabrica/pkg/fabrica"
	"github.com/openchami/named-resource-service/apis/named-resource-service.openchami.org/v1"
	"github.com/openchami/named-resource-service/internal/storage/ent"
	entnamed "github.com/openchami/named-resource-service/internal/storage/ent/named"
)

// ToEntNamed converts a Fabrica Named resource to an Ent Named create builder.
//
// Hybrid dedicated storage: the full spec is serialized into the spec_data JSON
// column (source of truth), and annotated/indexed scalar fields are also written
// to their promoted spec_ columns so database constraints and indexes apply.
func ToEntNamed(ctx context.Context, client *ent.Client, resource *v1.Named) (*ent.NamedCreate, error) {
	// Serialize the spec, scrubbing sensitive/hashed fields from the JSON copy.
	specForStorage := resource.Spec
	specData, err := json.Marshal(specForStorage)
	if err != nil {
		return nil, fmt.Errorf("marshal Named spec: %w", err)
	}

	create := client.Named.Create().
		SetUID(resource.Metadata.UID).
		SetName(resource.Metadata.Name).
		SetAPIVersion(resource.APIVersion).
		SetKind(resource.Kind).
		SetCreatedAt(resource.Metadata.CreatedAt).
		SetUpdatedAt(resource.Metadata.UpdatedAt).
		SetSpecData(specData)

	// Promoted spec columns (hashed values are hashed by an Ent hook on create).
	create = create.SetSpecName(resource.Spec.Name)
	create = create.SetSpecAltName(resource.Spec.AltName)
	create = create.SetSpecNumber(resource.Spec.Number)
	create = create.SetSpecSomethingOrNothing(resource.Spec.SomethingOrNothing)

	return create, nil
}

// FromEntNamed converts an Ent Named entity to a Fabrica Named resource.
//
// The spec is rebuilt from the spec_data JSON column; promoted columns are only
// read back for fields scrubbed from the JSON (sensitive/hashed).
func FromEntNamed(ctx context.Context, entity *ent.Named) (*v1.Named, error) {
	res := &v1.Named{

		APIVersion: entity.APIVersion,
		Kind:       entity.Kind,
		Metadata: fabrica.Metadata{
			Name:        entity.Name,
			UID:         entity.UID,
			CreatedAt:   entity.CreatedAt,
			UpdatedAt:   entity.UpdatedAt,
			Labels:      make(map[string]string),
			Annotations: make(map[string]string),
		},
	}

	if len(entity.SpecData) > 0 {
		if err := json.Unmarshal(entity.SpecData, &res.Spec); err != nil {
			return nil, fmt.Errorf("unmarshal Named spec: %w", err)
		}
	}

	// Restore fields scrubbed from JSON (sensitive/hashed) from their columns.

	return res, nil
}

// UpdateNamedFromResource updates an Ent Named entity from a Fabrica resource.
// Respects immutable field constraints; refreshes spec_data and mutable columns.
func UpdateNamedFromResource(ctx context.Context, update *ent.NamedUpdateOne, resource *v1.Named) error {
	specForStorage := resource.Spec
	specData, err := json.Marshal(specForStorage)
	if err != nil {
		return fmt.Errorf("marshal Named spec: %w", err)
	}

	update = update.
		SetUpdatedAt(resource.Metadata.UpdatedAt).
		SetSpecData(specData)

	// Update mutable promoted columns only.
	update = update.SetSpecName(resource.Spec.Name)
	update = update.SetSpecAltName(resource.Spec.AltName)
	update = update.SetSpecNumber(resource.Spec.Number)
	update = update.SetSpecSomethingOrNothing(resource.Spec.SomethingOrNothing)

	return nil
}

// QueryNamedByName queries a Named by name and optional namespace.
func QueryNamedByName(ctx context.Context, client *ent.Client, name string, namespace string) (*ent.Named, error) {
	query := client.Named.Query().
		Where(entnamed.NameEQ(name))

	return query.Only(ctx)
}

// ListNameds lists all Named resources, optionally filtered by namespace.
func ListNameds(ctx context.Context, client *ent.Client, namespace string) ([]*ent.Named, error) {
	query := client.Named.Query()

	return query.All(ctx)
}

// DeleteNamedByUID deletes a Named by UID.
func DeleteNamedByUID(ctx context.Context, client *ent.Client, uid string) error {
	_, err := client.Named.Delete().
		Where(entnamed.UIDEQ(uid)).
		Exec(ctx)
	return err
}
