// Code generated by Fabrica. This file will be replaced by Ent.
// SPDX-FileCopyrightText: Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
// SPDX-License-Identifier: MIT
//
// This is a temporary stub created during 'fabrica init' to prevent import errors.
// Run 'fabrica generate --storage' and Ent will replace this with real schema code.

package label

// Placeholder to prevent import errors - will be replaced by Ent-generated code
