// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//   1. Edit the template file: pkg/codegen/templates/server/openapi.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
//
package main

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/openchami/node-service-sqlite/apis/node-service.openchami.org/v1"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>node_service_sqlite API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "node_service_sqlite API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerNodePaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "node_service_sqlite",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJSONExample := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":   "node_service_sqlite API",
			"version": "1.0.0",
		},
	}
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
					Example: openAPIJSONExample,
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerNodePaths registers OpenAPI paths for Node resources
func registerNodePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Node{}, spec.Components.Schemas)
	spec.Components.Schemas["Node"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateNodeRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateNodeRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateNodeRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateNodeRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.NodeStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["NodeStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Nodes operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listNodes"
	listOp.Summary = "List all Node resources"
	listOp.Description = "Returns a list of all Node resources in the inventory"
	listOp.Tags = []string{"Node"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Node"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Node operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createNode"
	createOp.Summary = "Create a new Node resource"
	createOp.Description = "Creates a new Node resource with the provided specification"
	createOp.Tags = []string{"Node"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateNodeRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Node operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getNode"
	getOp.Summary = "Get a specific Node resource"
	getOp.Description = "Returns details of a specific Node resource by UID"
	getOp.Tags = []string{"Node"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Node operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateNode"
	updateOp.Summary = "Update a Node resource"
	updateOp.Description = "Updates an existing Node resource with new values"
	updateOp.Tags = []string{"Node"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateNodeRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Node operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchNode"
	patchOp.Summary = "Patch a Node resource"
	patchOp.Description = "Partially updates an existing Node resource using patch semantics"
	patchOp.Tags = []string{"Node"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Node",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Node status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateNodeStatus"
	updateStatusOp.Summary = "Update Node status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Node"
	updateStatusOp.Tags = []string{"Node"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/NodeStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Node"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Node status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchNodeStatus"
	patchStatusOp.Summary = "Patch Node status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Node"
	patchStatusOp.Tags = []string{"Node"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Node"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Node operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteNode"
	deleteOp.Summary = "Delete a Node resource"
	deleteOp.Description = "Removes a Node resource from the inventory"
	deleteOp.Tags = []string{"Node"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Node resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/nodes", collectionPath)
	spec.Paths.Set("/nodes/{uid}", itemPath)
	spec.Paths.Set("/nodes/{uid}/status", statusPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
