// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains client-side request/response models.
// Generated from: pkg/codegen/templates/client-models.go.tmpl
//
// To modify client models:
//   1. Edit the template file: pkg/codegen/templates/client-models.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// DEPRECATED: This template is a legacy stub. The actual client models are
// generated in models.go.tmpl and used by both server and client.
//
// Generated request types:
//   - CreateResourceRequest: Create operation with metadata
//   - UpdateResourceRequest: Update operation with partial fields
//   - DeleteResponse: Confirmation of deletion
//
// Note: This file contains TODO comments indicating that resource-specific
// fields should be added. Consider migrating to the unified models.go.tmpl
// approach or implementing spec field embedding.
//
// To implement full spec support:
//   1. Import resource packages
//   2. Embed ResourceSpec in request structs
//   3. Use json:",inline" tag for proper serialization
//
// To add validation:
//   1. Add validate tags (e.g., validate:"required,min=3")
//   2. Use go-playground/validator in client before sending
//

// Package client provides generated client-side request and response models.
package client

import (
	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/openchami/user-service/apis/named-resource-service.openchami.org/v1"
)

// CreateUserRequest represents a request to create a User (Advanced API)
// Use this when you need full control over metadata fields (labels, annotations).
// For simpler usage, see CreateUserSimple in the client.
type CreateUserRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" yaml:"metadata" validate:"required"`
	Spec        v1.UserSpec       `json:"spec" yaml:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// UpdateUserRequest represents a request to update a User (Advanced API)
// Use this when you need to update metadata fields along with the spec.
// For simpler usage, see UpdateUserSimple in the client.
type UpdateUserRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec        v1.UserSpec       `json:"spec,omitempty" yaml:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}
