// Code generated by Fabrica. This file will be replaced on first 'fabrica generate'.
// SPDX-FileCopyrightText: Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
// SPDX-License-Identifier: MIT
//
// This is a temporary stub created during 'fabrica init' to prevent import errors.
// Run 'fabrica generate --storage' to replace this with actual generated code.

package storage

// Placeholder to prevent import errors - will be replaced by generated code
