// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
package schema

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"golang.org/x/crypto/bcrypt"
)

// User holds the schema definition for the User entity.
// Hybrid dedicated schema: full spec in spec_data (JSON) + promoted columns.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		// Core identity fields
		field.String("uid").
			Unique().
			Immutable().
			NotEmpty().
			Comment("Unique identifier"),

		field.String("name").
			NotEmpty().
			MaxLen(253).
			Comment("Human-readable name"),

		field.String("namespace").
			Optional().
			Comment("Namespace for multi-tenancy"),

		// Resource metadata
		field.String("api_version").
			Default("v1").
			Comment("API version"),

		field.String("kind").
			Default("User").
			Comment("Resource kind"),

		// Timestamps
		field.Time("created_at").
			Immutable().
			Default(time.Now).
			Comment("Creation timestamp"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("Last update timestamp"),

		// Resource version for optimistic locking
		field.String("resource_version").
			Default("1").
			Comment("Resource version for ETags"),

		// Full spec as JSON (jsonb on PostgreSQL); source of truth on read.
		field.JSON("spec_data", json.RawMessage{}).
			Optional().
			Comment("Full UserSpec serialized as JSON"),

		// Promoted spec field: Username -> spec_username
		field.String("spec_username").
			Immutable().
			Unique().
			Optional().
			Comment("Username"),

		// Promoted spec field: Email -> spec_email
		field.String("spec_email").
			Unique().
			Optional().
			Comment("Email"),

		// Promoted spec field: Password -> spec_password
		field.String("spec_password").
			Sensitive().
			Immutable().
			SchemaType(map[string]string{
				dialect.Postgres: "varchar(60)",
				dialect.MySQL:    "varchar(60)",
				dialect.SQLite:   "TEXT",
			}).
			Optional().
			Comment("Password (hashed with bcrypt)"),

		// Promoted spec field: Role -> spec_role
		field.String("spec_role").
			Default("user").
			Optional().
			Comment("Role"),

		// Promoted spec field: Active -> spec_active
		field.Bool("spec_active").
			Default(true).
			Optional().
			Comment("Active"),
	}
}

// Indexes of the User.
func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("uid").Unique(),
		index.Fields("name", "namespace"),
		// B-tree index for Username
		index.Fields("spec_username"),
		// B-tree index for Email
		index.Fields("spec_email"),
		// B-tree index for Role
		index.Fields("spec_role"),

		// Composite index idx_user_login (btree, unique)
		index.Fields(
			"spec_username",
			"spec_email",
		).
			Unique().
			StorageKey("idx_user_login"),
	}
}

// Hooks of the User.
func (User) Hooks() []ent.Hook {
	return []ent.Hook{
		// Hash Password with bcrypt on create.
		//
		// Access goes through ent.Mutation's untyped Field/SetField, keyed by
		// the promoted COLUMN name, because *ent.UserMutation is generated
		// FROM this package and cannot be named here.
		func(next ent.Mutator) ent.Mutator {
			return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				if m.Op().Is(ent.OpCreate) {
					if raw, exists := m.Field("spec_password"); exists {
						value, ok := raw.(string)
						if !ok {
							return nil, fmt.Errorf("hash Password: expected string, got %T", raw)
						}
						hashed, err := bcrypt.GenerateFromPassword([]byte(value), 12)
						if err != nil {
							return nil, fmt.Errorf("hash Password: %w", err)
						}
						if err := m.SetField("spec_password", string(hashed)); err != nil {
							return nil, fmt.Errorf("set hashed Password: %w", err)
						}
					}
				}
				return next.Mutate(ctx, m)
			})
		},
	}
}
