// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
package schema

import (
	"encoding/json"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Named holds the schema definition for the Named entity.
// Hybrid dedicated schema: full spec in spec_data (JSON) + promoted columns.
type Named struct {
	ent.Schema
}

// Fields of the Named.
func (Named) Fields() []ent.Field {
	return []ent.Field{
		// Core identity fields
		field.String("uid").
			Unique().
			Immutable().
			NotEmpty().
			Comment("Unique identifier"),

		field.String("name").
			NotEmpty().
			MaxLen(253).
			Comment("Human-readable name"),

		field.String("namespace").
			Optional().
			Comment("Namespace for multi-tenancy"),

		// Resource metadata
		field.String("api_version").
			Default("v1").
			Comment("API version"),

		field.String("kind").
			Default("Named").
			Comment("Resource kind"),

		// Timestamps
		field.Time("created_at").
			Immutable().
			Default(time.Now).
			Comment("Creation timestamp"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("Last update timestamp"),

		// Resource version for optimistic locking
		field.String("resource_version").
			Default("1").
			Comment("Resource version for ETags"),

		// Full spec as JSON (jsonb on PostgreSQL); source of truth on read.
		field.JSON("spec_data", json.RawMessage{}).
			Optional().
			Comment("Full NamedSpec serialized as JSON"),

		// Promoted spec field: Name -> spec_name
		field.String("spec_name").
			Unique().
			Optional().
			Comment("Name"),

		// Promoted spec field: AltName -> spec_alt_name
		field.String("spec_alt_name").
			MaxLen(64).
			NotEmpty().
			Comment("AltName"),

		// Promoted spec field: Number -> spec_number
		field.Int("spec_number").
			Default(0).
			Optional().
			Comment("Number"),

		// Promoted spec field: SomethingOrNothing -> spec_something_or_nothing
		field.String("spec_something_or_nothing").
			Optional().
			Comment("SomethingOrNothing"),
	}
}

// Indexes of the Named.
func (Named) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("uid").Unique(),
		index.Fields("name", "namespace"),
		// B-tree index for Name
		index.Fields("spec_name").
			StorageKey("idx_named_name"),

		// Composite index idx_named_altname_name (btree, unique)
		index.Fields(
			"spec_alt_name",
			"spec_name",
		).
			Unique().
			StorageKey("idx_named_altname_name"),
	}
}

// Hooks of the Named.
func (Named) Hooks() []ent.Hook {
	return []ent.Hook{}
}
