// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Annotation is the predicate function for annotation builders.
type Annotation func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Named is the predicate function for named builders.
type Named func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)
