// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/server/openapi.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/openchami/inventory-service/apis/inventory-service.openchami.org/v1"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>inventory_service API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "inventory_service API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerComponentPaths(spec)
	registerComponentEndpointPaths(spec)
	registerEthernetInterfacePaths(spec)
	registerGroupPaths(spec)
	registerHardwarePaths(spec)
	registerRedfishEndpointPaths(spec)
	registerServiceEndpointPaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "inventory_service",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJSONExample := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":   "inventory_service API",
			"version": "1.0.0",
		},
	}
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
					Example: openAPIJSONExample,
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerComponentPaths registers OpenAPI paths for Component resources
func registerComponentPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Component{}, spec.Components.Schemas)
	spec.Components.Schemas["Component"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateComponentRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateComponentRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateComponentRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateComponentRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ComponentStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["ComponentStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Components operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listComponents"
	listOp.Summary = "List all Component resources"
	listOp.Description = "Returns a list of all Component resources in the inventory"
	listOp.Tags = []string{"Component"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Component"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Component operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createComponent"
	createOp.Summary = "Create a new Component resource"
	createOp.Description = "Creates a new Component resource with the provided specification"
	createOp.Tags = []string{"Component"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateComponentRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Component",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Component operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getComponent"
	getOp.Summary = "Get a specific Component resource"
	getOp.Description = "Returns details of a specific Component resource by UID"
	getOp.Tags = []string{"Component"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Component",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Component operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateComponent"
	updateOp.Summary = "Update a Component resource"
	updateOp.Description = "Updates an existing Component resource with new values"
	updateOp.Tags = []string{"Component"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateComponentRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Component",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Component operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchComponent"
	patchOp.Summary = "Patch a Component resource"
	patchOp.Description = "Partially updates an existing Component resource using patch semantics"
	patchOp.Tags = []string{"Component"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Component",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Component status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateComponentStatus"
	updateStatusOp.Summary = "Update Component status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Component"
	updateStatusOp.Tags = []string{"Component"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ComponentStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Component"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Component status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchComponentStatus"
	patchStatusOp.Summary = "Patch Component status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Component"
	patchStatusOp.Tags = []string{"Component"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Component"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Component operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteComponent"
	deleteOp.Summary = "Delete a Component resource"
	deleteOp.Description = "Removes a Component resource from the inventory"
	deleteOp.Tags = []string{"Component"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Component resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/components", collectionPath)
	spec.Paths.Set("/components/{uid}", itemPath)
	spec.Paths.Set("/components/{uid}/status", statusPath)
}

// registerComponentEndpointPaths registers OpenAPI paths for ComponentEndpoint resources
func registerComponentEndpointPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ComponentEndpoint{}, spec.Components.Schemas)
	spec.Components.Schemas["ComponentEndpoint"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateComponentEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateComponentEndpointRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateComponentEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateComponentEndpointRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ComponentEndpointStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["ComponentEndpointStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List ComponentEndpoints operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listComponentEndpoints"
	listOp.Summary = "List all ComponentEndpoint resources"
	listOp.Description = "Returns a list of all ComponentEndpoint resources in the inventory"
	listOp.Tags = []string{"ComponentEndpoint"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/ComponentEndpoint"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create ComponentEndpoint operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createComponentEndpoint"
	createOp.Summary = "Create a new ComponentEndpoint resource"
	createOp.Description = "Creates a new ComponentEndpoint resource with the provided specification"
	createOp.Tags = []string{"ComponentEndpoint"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateComponentEndpointRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ComponentEndpoint",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get ComponentEndpoint operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getComponentEndpoint"
	getOp.Summary = "Get a specific ComponentEndpoint resource"
	getOp.Description = "Returns details of a specific ComponentEndpoint resource by UID"
	getOp.Tags = []string{"ComponentEndpoint"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ComponentEndpoint",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update ComponentEndpoint operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateComponentEndpoint"
	updateOp.Summary = "Update a ComponentEndpoint resource"
	updateOp.Description = "Updates an existing ComponentEndpoint resource with new values"
	updateOp.Tags = []string{"ComponentEndpoint"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateComponentEndpointRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ComponentEndpoint",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch ComponentEndpoint operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchComponentEndpoint"
	patchOp.Summary = "Patch a ComponentEndpoint resource"
	patchOp.Description = "Partially updates an existing ComponentEndpoint resource using patch semantics"
	patchOp.Tags = []string{"ComponentEndpoint"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ComponentEndpoint",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update ComponentEndpoint status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateComponentEndpointStatus"
	updateStatusOp.Summary = "Update ComponentEndpoint status"
	updateStatusOp.Description = "Updates only the status subresource for an existing ComponentEndpoint"
	updateStatusOp.Tags = []string{"ComponentEndpoint"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ComponentEndpointStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ComponentEndpoint"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch ComponentEndpoint status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchComponentEndpointStatus"
	patchStatusOp.Summary = "Patch ComponentEndpoint status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing ComponentEndpoint"
	patchStatusOp.Tags = []string{"ComponentEndpoint"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ComponentEndpoint"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete ComponentEndpoint operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteComponentEndpoint"
	deleteOp.Summary = "Delete a ComponentEndpoint resource"
	deleteOp.Description = "Removes a ComponentEndpoint resource from the inventory"
	deleteOp.Tags = []string{"ComponentEndpoint"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the ComponentEndpoint resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/componentendpoints", collectionPath)
	spec.Paths.Set("/componentendpoints/{uid}", itemPath)
	spec.Paths.Set("/componentendpoints/{uid}/status", statusPath)
}

// registerEthernetInterfacePaths registers OpenAPI paths for EthernetInterface resources
func registerEthernetInterfacePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.EthernetInterface{}, spec.Components.Schemas)
	spec.Components.Schemas["EthernetInterface"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateEthernetInterfaceRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateEthernetInterfaceRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateEthernetInterfaceRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateEthernetInterfaceRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.EthernetInterfaceStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["EthernetInterfaceStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List EthernetInterfaces operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listEthernetInterfaces"
	listOp.Summary = "List all EthernetInterface resources"
	listOp.Description = "Returns a list of all EthernetInterface resources in the inventory"
	listOp.Tags = []string{"EthernetInterface"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/EthernetInterface"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create EthernetInterface operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createEthernetInterface"
	createOp.Summary = "Create a new EthernetInterface resource"
	createOp.Description = "Creates a new EthernetInterface resource with the provided specification"
	createOp.Tags = []string{"EthernetInterface"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateEthernetInterfaceRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/EthernetInterface",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get EthernetInterface operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getEthernetInterface"
	getOp.Summary = "Get a specific EthernetInterface resource"
	getOp.Description = "Returns details of a specific EthernetInterface resource by UID"
	getOp.Tags = []string{"EthernetInterface"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/EthernetInterface",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update EthernetInterface operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateEthernetInterface"
	updateOp.Summary = "Update a EthernetInterface resource"
	updateOp.Description = "Updates an existing EthernetInterface resource with new values"
	updateOp.Tags = []string{"EthernetInterface"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateEthernetInterfaceRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/EthernetInterface",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch EthernetInterface operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchEthernetInterface"
	patchOp.Summary = "Patch a EthernetInterface resource"
	patchOp.Description = "Partially updates an existing EthernetInterface resource using patch semantics"
	patchOp.Tags = []string{"EthernetInterface"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/EthernetInterface",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update EthernetInterface status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateEthernetInterfaceStatus"
	updateStatusOp.Summary = "Update EthernetInterface status"
	updateStatusOp.Description = "Updates only the status subresource for an existing EthernetInterface"
	updateStatusOp.Tags = []string{"EthernetInterface"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/EthernetInterfaceStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/EthernetInterface"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch EthernetInterface status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchEthernetInterfaceStatus"
	patchStatusOp.Summary = "Patch EthernetInterface status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing EthernetInterface"
	patchStatusOp.Tags = []string{"EthernetInterface"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/EthernetInterface"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete EthernetInterface operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteEthernetInterface"
	deleteOp.Summary = "Delete a EthernetInterface resource"
	deleteOp.Description = "Removes a EthernetInterface resource from the inventory"
	deleteOp.Tags = []string{"EthernetInterface"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the EthernetInterface resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/ethernetinterfaces", collectionPath)
	spec.Paths.Set("/ethernetinterfaces/{uid}", itemPath)
	spec.Paths.Set("/ethernetinterfaces/{uid}/status", statusPath)
}

// registerGroupPaths registers OpenAPI paths for Group resources
func registerGroupPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Group{}, spec.Components.Schemas)
	spec.Components.Schemas["Group"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateGroupRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateGroupRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateGroupRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateGroupRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.GroupStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["GroupStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Groups operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listGroups"
	listOp.Summary = "List all Group resources"
	listOp.Description = "Returns a list of all Group resources in the inventory"
	listOp.Tags = []string{"Group"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Group"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Group operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createGroup"
	createOp.Summary = "Create a new Group resource"
	createOp.Description = "Creates a new Group resource with the provided specification"
	createOp.Tags = []string{"Group"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateGroupRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Group operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getGroup"
	getOp.Summary = "Get a specific Group resource"
	getOp.Description = "Returns details of a specific Group resource by UID"
	getOp.Tags = []string{"Group"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Group operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateGroup"
	updateOp.Summary = "Update a Group resource"
	updateOp.Description = "Updates an existing Group resource with new values"
	updateOp.Tags = []string{"Group"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateGroupRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Group operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchGroup"
	patchOp.Summary = "Patch a Group resource"
	patchOp.Description = "Partially updates an existing Group resource using patch semantics"
	patchOp.Tags = []string{"Group"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Group",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Group status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateGroupStatus"
	updateStatusOp.Summary = "Update Group status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Group"
	updateStatusOp.Tags = []string{"Group"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/GroupStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Group"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Group status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchGroupStatus"
	patchStatusOp.Summary = "Patch Group status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Group"
	patchStatusOp.Tags = []string{"Group"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Group"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Group operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteGroup"
	deleteOp.Summary = "Delete a Group resource"
	deleteOp.Description = "Removes a Group resource from the inventory"
	deleteOp.Tags = []string{"Group"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Group resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/groups", collectionPath)
	spec.Paths.Set("/groups/{uid}", itemPath)
	spec.Paths.Set("/groups/{uid}/status", statusPath)
}

// registerHardwarePaths registers OpenAPI paths for Hardware resources
func registerHardwarePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Hardware{}, spec.Components.Schemas)
	spec.Components.Schemas["Hardware"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateHardwareRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateHardwareRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateHardwareRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateHardwareRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.HardwareStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["HardwareStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List Hardwares operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listHardwares"
	listOp.Summary = "List all Hardware resources"
	listOp.Description = "Returns a list of all Hardware resources in the inventory"
	listOp.Tags = []string{"Hardware"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Hardware"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create Hardware operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createHardware"
	createOp.Summary = "Create a new Hardware resource"
	createOp.Description = "Creates a new Hardware resource with the provided specification"
	createOp.Tags = []string{"Hardware"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateHardwareRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Hardware",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get Hardware operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getHardware"
	getOp.Summary = "Get a specific Hardware resource"
	getOp.Description = "Returns details of a specific Hardware resource by UID"
	getOp.Tags = []string{"Hardware"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Hardware",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update Hardware operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateHardware"
	updateOp.Summary = "Update a Hardware resource"
	updateOp.Description = "Updates an existing Hardware resource with new values"
	updateOp.Tags = []string{"Hardware"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateHardwareRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Hardware",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch Hardware operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchHardware"
	patchOp.Summary = "Patch a Hardware resource"
	patchOp.Description = "Partially updates an existing Hardware resource using patch semantics"
	patchOp.Tags = []string{"Hardware"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/Hardware",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update Hardware status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateHardwareStatus"
	updateStatusOp.Summary = "Update Hardware status"
	updateStatusOp.Description = "Updates only the status subresource for an existing Hardware"
	updateStatusOp.Tags = []string{"Hardware"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/HardwareStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Hardware"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch Hardware status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchHardwareStatus"
	patchStatusOp.Summary = "Patch Hardware status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing Hardware"
	patchStatusOp.Tags = []string{"Hardware"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/Hardware"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete Hardware operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteHardware"
	deleteOp.Summary = "Delete a Hardware resource"
	deleteOp.Description = "Removes a Hardware resource from the inventory"
	deleteOp.Tags = []string{"Hardware"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the Hardware resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/hardwares", collectionPath)
	spec.Paths.Set("/hardwares/{uid}", itemPath)
	spec.Paths.Set("/hardwares/{uid}/status", statusPath)
}

// registerRedfishEndpointPaths registers OpenAPI paths for RedfishEndpoint resources
func registerRedfishEndpointPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.RedfishEndpoint{}, spec.Components.Schemas)
	spec.Components.Schemas["RedfishEndpoint"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateRedfishEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateRedfishEndpointRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateRedfishEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateRedfishEndpointRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.RedfishEndpointStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["RedfishEndpointStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List RedfishEndpoints operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listRedfishEndpoints"
	listOp.Summary = "List all RedfishEndpoint resources"
	listOp.Description = "Returns a list of all RedfishEndpoint resources in the inventory"
	listOp.Tags = []string{"RedfishEndpoint"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/RedfishEndpoint"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create RedfishEndpoint operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createRedfishEndpoint"
	createOp.Summary = "Create a new RedfishEndpoint resource"
	createOp.Description = "Creates a new RedfishEndpoint resource with the provided specification"
	createOp.Tags = []string{"RedfishEndpoint"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateRedfishEndpointRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RedfishEndpoint",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get RedfishEndpoint operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getRedfishEndpoint"
	getOp.Summary = "Get a specific RedfishEndpoint resource"
	getOp.Description = "Returns details of a specific RedfishEndpoint resource by UID"
	getOp.Tags = []string{"RedfishEndpoint"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RedfishEndpoint",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update RedfishEndpoint operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateRedfishEndpoint"
	updateOp.Summary = "Update a RedfishEndpoint resource"
	updateOp.Description = "Updates an existing RedfishEndpoint resource with new values"
	updateOp.Tags = []string{"RedfishEndpoint"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateRedfishEndpointRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RedfishEndpoint",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch RedfishEndpoint operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchRedfishEndpoint"
	patchOp.Summary = "Patch a RedfishEndpoint resource"
	patchOp.Description = "Partially updates an existing RedfishEndpoint resource using patch semantics"
	patchOp.Tags = []string{"RedfishEndpoint"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RedfishEndpoint",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update RedfishEndpoint status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateRedfishEndpointStatus"
	updateStatusOp.Summary = "Update RedfishEndpoint status"
	updateStatusOp.Description = "Updates only the status subresource for an existing RedfishEndpoint"
	updateStatusOp.Tags = []string{"RedfishEndpoint"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RedfishEndpointStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RedfishEndpoint"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch RedfishEndpoint status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchRedfishEndpointStatus"
	patchStatusOp.Summary = "Patch RedfishEndpoint status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing RedfishEndpoint"
	patchStatusOp.Tags = []string{"RedfishEndpoint"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RedfishEndpoint"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete RedfishEndpoint operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteRedfishEndpoint"
	deleteOp.Summary = "Delete a RedfishEndpoint resource"
	deleteOp.Description = "Removes a RedfishEndpoint resource from the inventory"
	deleteOp.Tags = []string{"RedfishEndpoint"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the RedfishEndpoint resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/redfishendpoints", collectionPath)
	spec.Paths.Set("/redfishendpoints/{uid}", itemPath)
	spec.Paths.Set("/redfishendpoints/{uid}/status", statusPath)
}

// registerServiceEndpointPaths registers OpenAPI paths for ServiceEndpoint resources
func registerServiceEndpointPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ServiceEndpoint{}, spec.Components.Schemas)
	spec.Components.Schemas["ServiceEndpoint"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateServiceEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateServiceEndpointRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateServiceEndpointRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateServiceEndpointRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.ServiceEndpointStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["ServiceEndpointStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List ServiceEndpoints operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listServiceEndpoints"
	listOp.Summary = "List all ServiceEndpoint resources"
	listOp.Description = "Returns a list of all ServiceEndpoint resources in the inventory"
	listOp.Tags = []string{"ServiceEndpoint"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/ServiceEndpoint"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create ServiceEndpoint operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createServiceEndpoint"
	createOp.Summary = "Create a new ServiceEndpoint resource"
	createOp.Description = "Creates a new ServiceEndpoint resource with the provided specification"
	createOp.Tags = []string{"ServiceEndpoint"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateServiceEndpointRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ServiceEndpoint",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get ServiceEndpoint operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getServiceEndpoint"
	getOp.Summary = "Get a specific ServiceEndpoint resource"
	getOp.Description = "Returns details of a specific ServiceEndpoint resource by UID"
	getOp.Tags = []string{"ServiceEndpoint"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ServiceEndpoint",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update ServiceEndpoint operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateServiceEndpoint"
	updateOp.Summary = "Update a ServiceEndpoint resource"
	updateOp.Description = "Updates an existing ServiceEndpoint resource with new values"
	updateOp.Tags = []string{"ServiceEndpoint"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateServiceEndpointRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ServiceEndpoint",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch ServiceEndpoint operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchServiceEndpoint"
	patchOp.Summary = "Patch a ServiceEndpoint resource"
	patchOp.Description = "Partially updates an existing ServiceEndpoint resource using patch semantics"
	patchOp.Tags = []string{"ServiceEndpoint"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ServiceEndpoint",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update ServiceEndpoint status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateServiceEndpointStatus"
	updateStatusOp.Summary = "Update ServiceEndpoint status"
	updateStatusOp.Description = "Updates only the status subresource for an existing ServiceEndpoint"
	updateStatusOp.Tags = []string{"ServiceEndpoint"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ServiceEndpointStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ServiceEndpoint"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch ServiceEndpoint status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchServiceEndpointStatus"
	patchStatusOp.Summary = "Patch ServiceEndpoint status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing ServiceEndpoint"
	patchStatusOp.Tags = []string{"ServiceEndpoint"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/ServiceEndpoint"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete ServiceEndpoint operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteServiceEndpoint"
	deleteOp.Summary = "Delete a ServiceEndpoint resource"
	deleteOp.Description = "Removes a ServiceEndpoint resource from the inventory"
	deleteOp.Tags = []string{"ServiceEndpoint"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the ServiceEndpoint resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/serviceendpoints", collectionPath)
	spec.Paths.Set("/serviceendpoints/{uid}", itemPath)
	spec.Paths.Set("/serviceendpoints/{uid}/status", statusPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
