// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /components (Component operations)
//   - /componentendpoints (ComponentEndpoint operations)
//   - /ethernetinterfaces (EthernetInterface operations)
//   - /groups (Group operations)
//   - /hardwares (Hardware operations)
//   - /redfishendpoints (RedfishEndpoint operations)
//   - /serviceendpoints (ServiceEndpoint operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("Component", "component")

	resource.RegisterResourcePrefix("ComponentEndpoint", "componentendpoint")

	resource.RegisterResourcePrefix("EthernetInterface", "ethernetinterface")

	resource.RegisterResourcePrefix("Group", "group")

	resource.RegisterResourcePrefix("Hardware", "hardware")

	resource.RegisterResourcePrefix("RedfishEndpoint", "redfishendpoint")

	resource.RegisterResourcePrefix("ServiceEndpoint", "serviceendpoint")

	return nil
}

// RegisterGeneratedRoutes registers all generated resource routes.
// The router passed to this function should already have middleware applied in main.go.
// Public service routes such as /health, /openapi.json, and /docs are registered
// in cmd/server/main.go so they remain outside auth middleware.
func RegisterGeneratedRoutes(r chi.Router) {
	// Routes inherit middleware from the router passed by main.go

	// Component routes
	r.Route("/components", func(resource chi.Router) {
		resource.Get("/", GetComponents)
		resource.Post("/", CreateComponent)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetComponent)
			item.Put("/", UpdateComponent)
			item.Patch("/", PatchComponent)
			item.Delete("/", DeleteComponent)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateComponentStatus)
				status.Patch("/", PatchComponentStatus)
			})
		})
	})

	// ComponentEndpoint routes
	r.Route("/componentendpoints", func(resource chi.Router) {
		resource.Get("/", GetComponentEndpoints)
		resource.Post("/", CreateComponentEndpoint)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetComponentEndpoint)
			item.Put("/", UpdateComponentEndpoint)
			item.Patch("/", PatchComponentEndpoint)
			item.Delete("/", DeleteComponentEndpoint)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateComponentEndpointStatus)
				status.Patch("/", PatchComponentEndpointStatus)
			})
		})
	})

	// EthernetInterface routes
	r.Route("/ethernetinterfaces", func(resource chi.Router) {
		resource.Get("/", GetEthernetInterfaces)
		resource.Post("/", CreateEthernetInterface)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetEthernetInterface)
			item.Put("/", UpdateEthernetInterface)
			item.Patch("/", PatchEthernetInterface)
			item.Delete("/", DeleteEthernetInterface)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateEthernetInterfaceStatus)
				status.Patch("/", PatchEthernetInterfaceStatus)
			})
		})
	})

	// Group routes
	r.Route("/groups", func(resource chi.Router) {
		resource.Get("/", GetGroups)
		resource.Post("/", CreateGroup)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetGroup)
			item.Put("/", UpdateGroup)
			item.Patch("/", PatchGroup)
			item.Delete("/", DeleteGroup)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateGroupStatus)
				status.Patch("/", PatchGroupStatus)
			})
		})
	})

	// Hardware routes
	r.Route("/hardwares", func(resource chi.Router) {
		resource.Get("/", GetHardwares)
		resource.Post("/", CreateHardware)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetHardware)
			item.Put("/", UpdateHardware)
			item.Patch("/", PatchHardware)
			item.Delete("/", DeleteHardware)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateHardwareStatus)
				status.Patch("/", PatchHardwareStatus)
			})
		})
	})

	// RedfishEndpoint routes
	r.Route("/redfishendpoints", func(resource chi.Router) {
		resource.Get("/", GetRedfishEndpoints)
		resource.Post("/", CreateRedfishEndpoint)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetRedfishEndpoint)
			item.Put("/", UpdateRedfishEndpoint)
			item.Patch("/", PatchRedfishEndpoint)
			item.Delete("/", DeleteRedfishEndpoint)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateRedfishEndpointStatus)
				status.Patch("/", PatchRedfishEndpointStatus)
			})
		})
	})

	// ServiceEndpoint routes
	r.Route("/serviceendpoints", func(resource chi.Router) {
		resource.Get("/", GetServiceEndpoints)
		resource.Post("/", CreateServiceEndpoint)
		resource.Route("/{uid}", func(item chi.Router) {
			item.Get("/", GetServiceEndpoint)
			item.Put("/", UpdateServiceEndpoint)
			item.Patch("/", PatchServiceEndpoint)
			item.Delete("/", DeleteServiceEndpoint)

			// Status subresource
			item.Route("/status", func(status chi.Router) {
				status.Put("/", UpdateServiceEndpointStatus)
				status.Patch("/", PatchServiceEndpointStatus)
			})
		})
	})

}
