// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/openchami/user-service/internal/storage/ent/predicate"
	"github.com/openchami/user-service/internal/storage/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *UserUpdate) SetNamespace(v string) *UserUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNamespace(v *string) *UserUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *UserUpdate) ClearNamespace() *UserUpdate {
	_u.mutation.ClearNamespace()
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *UserUpdate) SetAPIVersion(v string) *UserUpdate {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAPIVersion(v *string) *UserUpdate {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *UserUpdate) SetKind(v string) *UserUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UserUpdate) SetNillableKind(v *string) *UserUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *UserUpdate) SetResourceVersion(v string) *UserUpdate {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *UserUpdate) SetNillableResourceVersion(v *string) *UserUpdate {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetSpecData sets the "spec_data" field.
func (_u *UserUpdate) SetSpecData(v json.RawMessage) *UserUpdate {
	_u.mutation.SetSpecData(v)
	return _u
}

// AppendSpecData appends value to the "spec_data" field.
func (_u *UserUpdate) AppendSpecData(v json.RawMessage) *UserUpdate {
	_u.mutation.AppendSpecData(v)
	return _u
}

// ClearSpecData clears the value of the "spec_data" field.
func (_u *UserUpdate) ClearSpecData() *UserUpdate {
	_u.mutation.ClearSpecData()
	return _u
}

// SetSpecEmail sets the "spec_email" field.
func (_u *UserUpdate) SetSpecEmail(v string) *UserUpdate {
	_u.mutation.SetSpecEmail(v)
	return _u
}

// SetNillableSpecEmail sets the "spec_email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSpecEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetSpecEmail(*v)
	}
	return _u
}

// ClearSpecEmail clears the value of the "spec_email" field.
func (_u *UserUpdate) ClearSpecEmail() *UserUpdate {
	_u.mutation.ClearSpecEmail()
	return _u
}

// SetSpecRole sets the "spec_role" field.
func (_u *UserUpdate) SetSpecRole(v string) *UserUpdate {
	_u.mutation.SetSpecRole(v)
	return _u
}

// SetNillableSpecRole sets the "spec_role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSpecRole(v *string) *UserUpdate {
	if v != nil {
		_u.SetSpecRole(*v)
	}
	return _u
}

// ClearSpecRole clears the value of the "spec_role" field.
func (_u *UserUpdate) ClearSpecRole() *UserUpdate {
	_u.mutation.ClearSpecRole()
	return _u
}

// SetSpecActive sets the "spec_active" field.
func (_u *UserUpdate) SetSpecActive(v bool) *UserUpdate {
	_u.mutation.SetSpecActive(v)
	return _u
}

// SetNillableSpecActive sets the "spec_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSpecActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetSpecActive(*v)
	}
	return _u
}

// ClearSpecActive clears the value of the "spec_active" field.
func (_u *UserUpdate) ClearSpecActive() *UserUpdate {
	_u.mutation.ClearSpecActive()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if user.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(user.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(user.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(user.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(user.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(user.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecData(); ok {
		_spec.SetField(user.FieldSpecData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldSpecData, value)
		})
	}
	if _u.mutation.SpecDataCleared() {
		_spec.ClearField(user.FieldSpecData, field.TypeJSON)
	}
	if _u.mutation.SpecUsernameCleared() {
		_spec.ClearField(user.FieldSpecUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SpecEmail(); ok {
		_spec.SetField(user.FieldSpecEmail, field.TypeString, value)
	}
	if _u.mutation.SpecEmailCleared() {
		_spec.ClearField(user.FieldSpecEmail, field.TypeString)
	}
	if _u.mutation.SpecPasswordCleared() {
		_spec.ClearField(user.FieldSpecPassword, field.TypeString)
	}
	if value, ok := _u.mutation.SpecRole(); ok {
		_spec.SetField(user.FieldSpecRole, field.TypeString, value)
	}
	if _u.mutation.SpecRoleCleared() {
		_spec.ClearField(user.FieldSpecRole, field.TypeString)
	}
	if value, ok := _u.mutation.SpecActive(); ok {
		_spec.SetField(user.FieldSpecActive, field.TypeBool, value)
	}
	if _u.mutation.SpecActiveCleared() {
		_spec.ClearField(user.FieldSpecActive, field.TypeBool)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *UserUpdateOne) SetNamespace(v string) *UserUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNamespace(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *UserUpdateOne) ClearNamespace() *UserUpdateOne {
	_u.mutation.ClearNamespace()
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *UserUpdateOne) SetAPIVersion(v string) *UserUpdateOne {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAPIVersion(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *UserUpdateOne) SetKind(v string) *UserUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableKind(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *UserUpdateOne) SetResourceVersion(v string) *UserUpdateOne {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableResourceVersion(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetSpecData sets the "spec_data" field.
func (_u *UserUpdateOne) SetSpecData(v json.RawMessage) *UserUpdateOne {
	_u.mutation.SetSpecData(v)
	return _u
}

// AppendSpecData appends value to the "spec_data" field.
func (_u *UserUpdateOne) AppendSpecData(v json.RawMessage) *UserUpdateOne {
	_u.mutation.AppendSpecData(v)
	return _u
}

// ClearSpecData clears the value of the "spec_data" field.
func (_u *UserUpdateOne) ClearSpecData() *UserUpdateOne {
	_u.mutation.ClearSpecData()
	return _u
}

// SetSpecEmail sets the "spec_email" field.
func (_u *UserUpdateOne) SetSpecEmail(v string) *UserUpdateOne {
	_u.mutation.SetSpecEmail(v)
	return _u
}

// SetNillableSpecEmail sets the "spec_email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSpecEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSpecEmail(*v)
	}
	return _u
}

// ClearSpecEmail clears the value of the "spec_email" field.
func (_u *UserUpdateOne) ClearSpecEmail() *UserUpdateOne {
	_u.mutation.ClearSpecEmail()
	return _u
}

// SetSpecRole sets the "spec_role" field.
func (_u *UserUpdateOne) SetSpecRole(v string) *UserUpdateOne {
	_u.mutation.SetSpecRole(v)
	return _u
}

// SetNillableSpecRole sets the "spec_role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSpecRole(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSpecRole(*v)
	}
	return _u
}

// ClearSpecRole clears the value of the "spec_role" field.
func (_u *UserUpdateOne) ClearSpecRole() *UserUpdateOne {
	_u.mutation.ClearSpecRole()
	return _u
}

// SetSpecActive sets the "spec_active" field.
func (_u *UserUpdateOne) SetSpecActive(v bool) *UserUpdateOne {
	_u.mutation.SetSpecActive(v)
	return _u
}

// SetNillableSpecActive sets the "spec_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSpecActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetSpecActive(*v)
	}
	return _u
}

// ClearSpecActive clears the value of the "spec_active" field.
func (_u *UserUpdateOne) ClearSpecActive() *UserUpdateOne {
	_u.mutation.ClearSpecActive()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if user.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(user.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(user.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(user.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(user.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(user.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SpecData(); ok {
		_spec.SetField(user.FieldSpecData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecData(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldSpecData, value)
		})
	}
	if _u.mutation.SpecDataCleared() {
		_spec.ClearField(user.FieldSpecData, field.TypeJSON)
	}
	if _u.mutation.SpecUsernameCleared() {
		_spec.ClearField(user.FieldSpecUsername, field.TypeString)
	}
	if value, ok := _u.mutation.SpecEmail(); ok {
		_spec.SetField(user.FieldSpecEmail, field.TypeString, value)
	}
	if _u.mutation.SpecEmailCleared() {
		_spec.ClearField(user.FieldSpecEmail, field.TypeString)
	}
	if _u.mutation.SpecPasswordCleared() {
		_spec.ClearField(user.FieldSpecPassword, field.TypeString)
	}
	if value, ok := _u.mutation.SpecRole(); ok {
		_spec.SetField(user.FieldSpecRole, field.TypeString, value)
	}
	if _u.mutation.SpecRoleCleared() {
		_spec.ClearField(user.FieldSpecRole, field.TypeString)
	}
	if value, ok := _u.mutation.SpecActive(); ok {
		_spec.SetField(user.FieldSpecActive, field.TypeBool, value)
	}
	if _u.mutation.SpecActiveCleared() {
		_spec.ClearField(user.FieldSpecActive, field.TypeBool)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
